### ISSUE TITLE
Don’t Work on iOS 16

### ISSUE THREAD

**Issue by EDnny12** [ABausG/home_widget#101]
initiallyLaunchedFromHomeWidget And widgetClicked don’t work on iOS 16.

Before updating, it worked well.

How can i fix this? 

Android Works!!

**Comment by desmeit** [comment]
for me it is working on IOS 16.
Please check https://github.com/ABausG/home_widget/issues/72

**Comment by EDnny12** [comment]
It was working well, but after update no!

**Comment by moosalim** [comment]
> for me it is working on IOS 16. Please check #72

@desmeit can you please provide example of working flutter app with home widget in IOS 16

**Comment by fsayfitdinov** [comment]
I am having the same issue, is there any workarounds?

**Comment by fsayfitdinov** [comment]
For now, I could bypass this issue with universal links

**Comment by admincode1** [comment]
Any fix? am also having same issue.
Both initiallyLaunchedFromHomeWidget And widgetClicked not working on iOS 16.

**Comment by ABausG** [comment]
Are you testing on a real device or on the simulator?

For me the simulator is working as expected.

https://github.com/ABausG/home_widget/assets/7288963/27e2d2ad-7354-4693-9d53-8ec8ad0b4de0


Did you make sure that the link contains `homeWidget` as a queryParameter. https://github.com/ABausG/home_widget#ios

**Comment by admincode1** [comment]
The link I had didn't contain "homeWidget", once I updated it worked. 
Thanks @ABausG
