### ISSUE TITLE
Builds failing on Android after upgrade

### ISSUE THREAD

**Issue by bradrushworth** [ABausG/home_widget#102]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':home_widget' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10

**Comment by bradrushworth** [comment]
classpath 'com.android.tools.build:gradle:7.3.0'
seems to be the version that breaks.

**Comment by acrossoffwest** [comment]
> ```
>     classpath 'com.android.tools.build:gradle:7.3.0'
> ```
> 
> seems to be the version that breaks.

thx, you were right
