### ISSUE TITLE
(iOS) After creating a 2nd home widget, saved data is not being found for new data fields 

### ISSUE THREAD

**Issue by jonas-zebari** [ABausG/home_widget#106]
I used home_widget to successfully implement a simple home widget which displayed a string, and I could update that string later from within the app. I recently started to work on adding a 2nd home widget to the app and I cannot get access to any of the new fields I'm trying to save for this widget from within the iOS home widget code. This is what I have:

When saving the data:
```dart
await HomeWidget.saveWidgetData<String>('tip_of_the_day_content_id', tipOfTheDay.contentId);
await HomeWidget.saveWidgetData<String>('tip_of_the_day_title', tipOfTheDay.title);
await HomeWidget.saveWidgetData<String>('tip_of_the_day_image_url', tipOfTheDay.imageUrl);
await HomeWidget.saveWidgetData<int>('tip_of_the_day_like_count', tipOfTheDay.likeCount);
```
All of these function calls return `true`. If I then try to get the saved data from Dart everything works fine. However, in iOS, all of the relevant fields are not being returned from UserDefaults:
```swift
let data = UserDefaults.init(suiteName: groupID)
let contentID = data?.string(forKey: "tip_of_the_day_content_id")
let title = data?.string(forKey: "tip_of_the_day_title")
let imageURL = data?.string(forKey: "tip_of_the_day_image_url")
let likeCount = data?.integer(forKey: "tip_of_the_day_like_count")
```
All of these values are returning `nil` and I'm really not sure why. My first thought is that when I make the call to update the widget I am using the wrong iOS name, but I've copy and pasted it from Xcode so I'm not sure what else the value for that could be.

**Comment by jonas-zebari** [comment]
I can provide any additional information needed.

**Comment by jonas-zebari** [comment]
@ABausG I've double checked that my "iOSName" when updating the widget from dart matches exactly the value in the "kind" in the swiftui widget. I'm not sure where to go from there. Any help would be appreciated :)

**Comment by SoMWbRa** [comment]
Maybe you don't setup "AppGroup" for runner and widget extension
