### ISSUE TITLE
Loading between updates

### ISSUE THREAD

**Issue by thize** [ABausG/home_widget#110]
When i call  await HomeWidget.updateWidget to change my Widget tab or info, the android widget has a fast change to "Loading..." and then the new data appears, is there any way to avoid this?

https://user-images.githubusercontent.com/10541221/206686211-90104a32-7739-49d9-b56a-f71ca101a702.mp4

**Comment by RamiroGarrido** [comment]
This is 100% a task for yourself friend, this has nothing to do with the library home_widget...Try to add a time delay manually of a couple of seconds if you want to show the "Loading..." text, but I don't recommend it. Why does the user have to wait to see a result? lmao
