### ISSUE TITLE
Does not work after version 3.0.5 of flutter (home_widget 0.1.6)

### ISSUE THREAD

**Issue by baststar** [ABausG/home_widget#114]
If you use flutter > 3.0.5 you get this error if you build in release-mode and try a buttonclick on the widget:
https://stackoverflow.com/questions/74675682/flutter-dart-error-dart-lookuplibrary-library-packagehome-widget-home-widget

the solution with 
@pragma('vm:entry-point')
doesnt work for me

Plugin works with this setup:

pubspec.yaml
environment:
  sdk: '>=2.17.0 <3.0.0'

with flutter version 3.0.5

"--release flag won't let service extensions run [(see the docs here)](https://docs.flutter.dev/testing/build-modes)."
https://stackoverflow.com/a/73613366

"Service extensions are disabled."
https://docs.flutter.dev/testing/build-modes#release

EDIT:
oh maybe it needs to be @pragma("vm:entry-point") with doublequotes instead of @pragma('vm:entry-point')
it worked now with flutter 3.3.10
(and environment:
  sdk: '>=2.17.6 <3.0.0')

**Comment by ABausG** [comment]
@baststar can this be closed then?
