### ISSUE TITLE
Writing to user Defaults not allowed on iPhone 11 and older despite IOS level being 16.1

### ISSUE THREAD

**Issue by asofdev** [ABausG/home_widget#119]
IOS widget works with no problems on iPhone 12 and newer, however on iPhone 11 and older writing to user defaults is not allowed.

Calling .saveWidgetData() returns the following error (package name replaced with X's):

Couldn't read values in CFPrefsPlistSource<0x28164a500> (Domain: group.com.XXXXXXXX.XXXXX, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

Seems the line to point out is "Using kCFPreferencesAnyUser with a container is only allowed for System Containers".

GroupID matches on Runner target and widget target, and has been setup in developer account.

Would highly appreciate any help.

Thanks

**Comment by dukewan** [comment]
I have iPhone 13 Pro with iOS 16.2 but facing the same issue here.

**Comment by asofdev** [comment]
Okay the issue for me ended up being that the PNG's I was using in my widget were too large for iPhone 11 and older, this would cause the home widget to not render.

Making my PNG byte size much smaller solved my issue, but did not stop the referenced error from popping up.

- Is there a way we could catch an exception spawned by PNG's being too large for older models?
- Also still not sure what is causing the "CFPrefsPlistSource" error, but everything seems to be working fine now despite this error still displaying.

**Comment by ABausG** [comment]
The next version 0.3.0 will support saving Flutter Widgets as Screenshots and will save them as a File and store the path to that file as a home_widget variable.
I guess it would make sense to offer that functionality to have something along the lines of `saveImage(Uint8List bytes, {Key key})`.

**Comment by felipecastrosales** [comment]
I'm having a problem that may be related to this and I've tried a few different things to solve it, so far nothing.

```
[User Defaults] Couldn't read values in CFPrefsPlistSource<0x281a9a900> (Domain: group.com.felipecastrosales.home, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
```

Previously, my group name it was `group/felipecastrosaleshome`. 

---

Another question, for make this I need in fact the Developer Account (paying 99 USD) or not is necessary for testings?

**Comment by ABausG** [comment]
@felipecastrosales I am not 100% sure if it needs to be a paid account. You will definitely need an Apple Developer Account but I am not sure if you actually need to be on a paid account or if it would also work with a free one.
Would be interesting to see if it might actually work with a free one. Have you tried to create one on developer.apple.com ?

**Comment by felipecastrosales** [comment]
yes, I'm trying with free account @ABausG and this errror is showed. @ABausG.

Including, the UserDefaults always return the default value.

I'm following the [codelabs tutorial](https://codelabs.developers.google.com/flutter-home-screen-widgets).

**Comment by felipecastrosales** [comment]
I can fix this problem to me following [this suggestion (and my comment can help also](https://stackoverflow.com/questions/38275395/failed-to-read-values-in-cfprefsplistsource-ios-10#comment136094612_61556575).

Here: 

![image](https://github.com/ABausG/home_widget/assets/59374587/f47574e5-1d08-4146-8960-e868bcaa4285)

**Comment by bigjjjim** [comment]
I am having the same error as FelipeCastrosales. It works great on emulator with new iphone 15 but on my iphone 13 I am seeing the following message in the console: 

[User Defaults] Couldn't read values in CFPrefsPlistSource<0x282dba800> (Domain: group.moonwidget, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

And I am not able to see the home widget at all.

**Comment by bigjjjim** [comment]
I solved the problem of not seeing the widget on physical device by reducing the minimum target for the extension to a value equal to the current ios version on the phone (16.1). I am not so sure why but by creating the new extension it was given a minimum value of 16.4 while the minimum target of the runner was 11.0.
