### ISSUE TITLE
Mocking execution of delayed operations, widget cannot be updated

### ISSUE THREAD

**Issue by HLUO18-ford** [ABausG/home_widget#123]
Android 12. 
Simulate delayed operation in flutter logic, unable to refresh widget, lasts about 5 seconds or less.

<img width="645" alt="截屏2023-02-20 下午8 35 31" src="https://user-images.githubusercontent.com/40845028/220109638-e4a5f648-12d3-482d-b356-1558414beeb4.png">

**Comment by bakipasa66** [comment]
Have this on Android 13.
Happens with too many background callbacks at once.
I have a button on widget that updates the text on widget and it freezes when i click the button rapidly.

**Comment by HLUO18-ford** [comment]
> Have this on Android 13. Happens with too many background callbacks at once. I have a button on widget that updates the text on widget and it freezes when i click the button rapidly.

The current investigation found that the problem occurs with Android 12 and above.
An interesting phenomenon, the same JobIntentService Code in the Android native project is able to survive and work properly.
