### ISSUE TITLE
Update iOS home widget in terminated state

### ISSUE THREAD

**Issue by LoadJulz** [ABausG/home_widget#125]
I have implmented the home_widget package and I am fetching data from network in order to show them on the widget. I have the feeling that for iOS it doesn't update in background when the app is terminated (not in multitasking). Does anyone else have the same experience? I am working with workmanager. I have registered the task in my app delegate and also scheduled background fetches every 15 minutes there. If I use the background fetch debug method from Xcode everything works like charm. 

Anybody who can assist me with my problem?

**Comment by ABausG** [comment]
1. I assume the task itself is in work manager is executed when the app is in the terminated state?
2. Can you share (some) of the code in the work manager task
3. Is it `flutter_workmanager` that you are using? In that case (or I guess for other solutions similar thing) did you make sure that you register other plugins (mainly home_widget) for that Plugin? with `flutter_workmanager` it is described how to do in the readme https://github.com/ABausG/home_widget#background-update

**Comment by aidarbye** [comment]
In ios, there is no way to update widgets regularly through workmanager, instead, iOS has a mechanism with a Timeline from where you can make periodic requests.
