### ISSUE TITLE
 Error: No named parameter with the name 'view'

### ISSUE THREAD

**Issue by burhanaksendir** [ABausG/home_widget#141]
environment:
  sdk: ">=2.18.0 <4.0.0"
 
 dependencies: 
 home_widget: ^0.3.0

**Comment by ABausG** [comment]
What's the output of `flutter doctor`? Think you might need to upgrade your dart version

**Comment by burhanaksendir** [comment]
@ABausG 

[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4.1 22F82 darwin-arm64, locale tr-TR)
    • Flutter version 3.7.12 on channel stable at /Volumes/Media/Development/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

**Comment by mobin-sk** [comment]
Any update on this ?

**Comment by mobin-sk** [comment]
Okay upgrading flutter has fixed this problem 
My flutter doctor  : 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by burhanaksendir** [comment]
@ABausG Thanks.
