### ISSUE TITLE
Updating Remaining Time in Home Screen Widget When Application is Closed

### ISSUE THREAD

**Issue by burhanaksendir** [ABausG/home_widget#142]
I'm working on an application where users can create reminders by specifying custom dates. Some of these reminders are displayed as home screen widgets. However, I'm facing a challenge regarding updating the remaining time in the widget when the application is completely closed.

I would appreciate any guidance, roadmap, or simple examples on how I can achieve this. Specifically, I'm looking for a solution to keep the home screen widget updated with the remaining time until the target date, even when the application is not actively running.

**Comment by milindgoel15** [comment]
You can use work manager plugin to achieve this. In the callback dispatcher, update the home widget information with the remaining time left to the targeted date.

**Comment by ABausG** [comment]
You might want to try this https://developer.android.com/reference/android/widget/Chronometer For iOS use the `.timer` style https://stackoverflow.com/a/64054466

**Comment by burhanaksendir** [comment]
@ABausG @milindgoel15 Thank you very much for your help.
