### ISSUE TITLE
iOS 17 Interactive Widgets

### ISSUE THREAD

**Issue by bypass112** [ABausG/home_widget#150]
Hello, with the release for iOS 17 rolling out in September, will the home_widget Flutter package support[ interactive elements for Home Widgets for iOS](https://developer.apple.com/documentation/widgetkit/creating-a-widget-extension/#Add-dynamic-content-to-your-widget), like buttons?
There are a few [official examples](https://developer.apple.com/documentation/widgetkit/adding-interactivity-to-widgets-and-live-activities) on how to add interactivity to iOS Widgets, but I'm not sure it is compatible with your solution.
It also seems that there are [a few apps](https://youtu.be/UsIeymtCFaA?t=62) that already support Widget Interactivity, but most likely those are native.
Thank you!

**Comment by ABausG** [comment]
Yes this is on my radar to add. The general building blocks on the flutter side are already in place as interactivity is already working with the package on Android. I hope to manage to get it working before iOS 17 is released or at least close to the official release.

**Comment by kakopappa** [comment]
Great! Waiting for iOS17 for a while now. Any idea when dev branch will be ready to release.

**Comment by ABausG** [comment]
I'll need some more time to validate everything. But you should be able to use a prerelease version 0.4.0-alpha.0 already.
Check out the article I wrote for more info and an example: https://medium.com/@ABausG/interactive-homescreen-widgets-with-flutter-using-home-widget-83cb0706a417
