### ISSUE TITLE
HomeWidget.renderFlutterWidget() in isolates

### ISSUE THREAD

**Issue by imgarvish** [ABausG/home_widget#152]
Does `HomeWidget.renderFlutterWidget()` work in isolates? Or we can only use it in main thread?

**Comment by ctrl-aziz** [comment]
I tried it with `flutter_background_service` and `android_alarm_manager_plus` and it's work fine

**Comment by imgarvish** [comment]
thanks a lot! after using [this](https://github.com/ABausG/home_widget/pull/155) PR, i solved the issue ;)
