### ISSUE TITLE
data not update background and app closed

### ISSUE THREAD

**Issue by amirmalakie** [ABausG/home_widget#153]
I want to send data to the widget every 5 seconds in the backgrand . But I followed your code, and I didn't get any results.

**Comment by ABausG** [comment]
Some follow up questions:
1. What Platform are you on?
2. How are you trying to do updates?
3. Is it that all updates are not done to the widget? It might be that the system does not update the Widget as 5 seconds is under the update frequency the system usually allow the widgets.
4. What is your desired usecase that you need to update the widget that frequent?
