### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hyeonhh** [ABausG/home_widget#159]
<img width="359" alt="image" src="https://github.com/ABausG/home_widget/assets/96102917/26742801-88e0-4698-938c-0981c1dd5168">

1. If I import from the kotlin file, an error occurs in the es part. What should I do??
2. And in the flutter project, we are using sqlite to show the data in the db file on the screen. At this time, I want to make this data available on the home widget, is it possible?

**Comment by ABausG** [comment]
1. Did you do a `flutter pub get` to add it? Where does the File lay in the File Structure
2. Can't follow you 100% could you add some more examples of what you are trying to do? In principal if you have access to the data in the Flutter App you should be able to call `HomeWidget.saveData` from there. With the build in things it is not really possible to automatically sync your database with the widgets. However you should be able to tap into your database file from the WidgetProvider on the native side however that is not something this plugin is designed to do so I can't give much support there

**Comment by hyeonhh** [comment]
1. I updated it and it was imported normally!
2. Then, can I implement it if I use the WidgetProvider function on the native side?
My project structure is as below
First, there is a db file in the assets folder.
I'm reading this in flutter code and showing the data on the screen.
I want to make sure that the data you see on the screen of the app can also be viewed on the home screen widget.

Thank you so much for your reply!
