### ISSUE TITLE
home widget doesn't appear on main screen Samsung SM-A032

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [ABausG/home_widget#161]
I implemented this library, but I managed to install a widget on the main window of the device in the emulator, but on the Samsung SM-A032F it is not in the list of widgets

I used davinci: ^2.1.1
to simply convert the layout and transfer it to ImageView, but it works with the emulator, I don’t know what the problem might be

**Comment by ABausG** [comment]
This might be an issue with the launcher of the Samsung phone
