### ISSUE TITLE
Jetpack Glance provider

### ISSUE THREAD

**Issue by large** [ABausG/home_widget#165]
Hi, thank you for this great tool for widget.
I have recently created my first project with widgets and I wonder if there will be any support for provider related to Jetpack Glance?
Ref: https://developer.android.com/jetpack/compose/glance

I was thinking of your handly abstract class here: https://github.com/ABausG/home_widget/blob/main/android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetProvider.kt

When Glace is created it is inherted from `GlanceAppWidget()`

Per now I have tested the `HomeWidgetPlugin.getData(context)` and it works, but I would like to have events triggered on datachange (that I belive the provide will give?)

Best regards large (Android n00b atm...)

**Comment by ABausG** [comment]
Yes this is on the list for the future and already tracked by #134
