### ISSUE TITLE
Unresolved reference: HomeWidgetPlugin

### ISSUE THREAD

**Issue by cl-ement05** [ABausG/home_widget#166]
When trying to compile, flutter throws error saying HomeWidgetBackgroundService lines 40 and 79 make unresolved reference to HomeWidgetPlugin

Version used : 0.2.1
flutter version : 3.13.4

**Comment by cl-ement05** [comment]
Yes I did

**Comment by memoriasIT** [comment]
Removing the cache manually from pub cache, then flutter clean and get did fix it for me :)
