### ISSUE TITLE
Support for using flutter widgets as screen widget UI

### ISSUE THREAD

**Issue by laterdayi** [ABausG/home_widget#167]
This is a great repository, but I don't understand why I can't use flutter widgets as screen widget UI, can this optimize it? Because a lot of developers only do flutter and not Android or ios

**Comment by Codestian** [comment]
Its much more difficult to translate dart to native programming languages for widgets. A workaround is to take a screenshot of the flutter widget and render the image. Its actually easier to use native code for widgets.

**Comment by ABausG** [comment]
The operating systems only allow a certain subset of widgets and functionality on the Widgets to ensure performance on user's home screens. Unfortunately there is nothing we can do (right now). I personally believe that home_widget solves a lot of the issues though and building the widgets natively should be possible for all devs. Especially now that home_widget support Jetpack Glance in Version 0.5.0
