### ISSUE TITLE
after create widget_extension, then build and it was wrong

### ISSUE THREAD

**Issue by zhushenwudi** [ABausG/home_widget#173]
Hi, I just created the WidgetExtension component in xcode, configured the signature and reported an error
I see that there is arm64 on the log, I wonder if it is because this does not support m1 chip?

```
Showing All Errors Only
Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': ExtractAppIntentsMetadata
○ Target 'Runner' has copy command from '/Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/HomeWidgetExampleExtension.appex' to '/Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/PlugIns/HomeWidgetExampleExtension.appex'
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/HomeWidgetExampleExtension.appex' to '/Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/PlugIns/HomeWidgetExampleExtension.appex'


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/ExtractedAppShortcutsMetadata.stringsdata ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ExtractAppIntentsMetadata ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7-copy-files> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7-copy-files ->

node: <Copy /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/PlugIns/HomeWidgetExampleExtension.appex> ->

CYCLE POINT ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/PlugIns/HomeWidgetExampleExtension.appex /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/HomeWidgetExampleExtension.appex ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--copy-pods-resources> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--copy-pods-resources ->

node: /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-965E287B7A1A700919D47D5B-Pods-Runner-resources-Debug-input-files-14256e77c36899b681cf5814608677f7-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-965E287B7A1A700919D47D5B-Pods-Runner-resources-Debug-input-files-14256e77c36899b681cf5814608677f7-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks ->

node: /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-43C767853172FD48E98AC0CD-Pods-Runner-frameworks-Debug-input-files-7990220141752f9ec7e1c323478d263f-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/InputFileList-43C767853172FD48E98AC0CD-Pods-Runner-frameworks-Debug-input-files-7990220141752f9ec7e1c323478d263f-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

node: <execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->

node: /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/Info.plist/ ->

directoryTreeSignature: � ->

directoryContents: /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/Info.plist ->

node: /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/Info.plist ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/Info.plist /Users/hoshizora-rin/Documents/important/flutter/LoveLiveMusicPlayerMobile/ios/Runner/Info.plist ->

node: /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/PlugIns/HomeWidgetExampleExtension.appex ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/Runner.app/PlugIns/HomeWidgetExampleExtension.appex /Users/hoshizora-rin/Library/Developer/Xcode/DerivedData/Runner-fdeeaenbwnxyjjfddqpjonzojugk/Build/Products/Debug-iphoneos/HomeWidgetExampleExtension.appex
```

**Comment by ineffablesam** [comment]
Same error any Help @ABausG

**Comment by bypass112** [comment]
From reading this post: https://developer.apple.com/forums/thread/730974 this seems to be a new issue from mixing Xcode 15, with Flutter and having a iOS Home Widget added to the project.
The fix that worked for me whas from this:

> I was able to fix this by moving the Embed App Extensions, Embed Frameworks, and Embed Pods Frameworks to be performed before the Run Script build phase. I had just run into the issue in the Xcode 15.0 update and am building with Flutter w/ flavors.
> ![image](https://github.com/ABausG/home_widget/assets/82344714/ea96e781-f9de-4f2c-9f13-2ee8b1504894)

Basically I moved all Build phases (from Runner -> Build Phases -> Targets -> Runner) that contained "Embedded" word before the first "Run Script"
Can anyone else confirm this fixes the build process?

If everything is ok, maybe the README needs to be updated to include this fix.

**Comment by zhushenwudi** [comment]
great, it works well
<img width="403" alt="image" src="https://github.com/ABausG/home_widget/assets/30340027/b15fb466-b521-4f33-9fd9-b370ed5d66c0">

**Comment by ineffablesam** [comment]
> From reading this post: https://developer.apple.com/forums/thread/730974 this seems to be a new issue from mixing Xcode 15, with Flutter and having a iOS Home Widget added to the project. The fix that worked for me was from this:
> 
> > I was able to fix this by moving the Embed App Extensions, Embed Frameworks, and Embed Pods Frameworks to be performed before the Run Script build phase. I had just run into the issue in the Xcode 15.0 update and am building with Flutter w/ flavors.
> > ![image](https://user-images.githubusercontent.com/82344714/278280031-ea96e781-f9de-4f2c-9f13-2ee8b1504894.png)
> 
> Basically I moved all Build phases (from Runner -> Build Phases -> Targets -> Runner) that contained "Embedded" word before the first "Run Script" Can anyone else confirm this fixes the build process?
> 
> If everything is ok, maybe the README needs to be updated to include this fix.

This Works perfectly, Looks like the README need to be updates.

**Comment by ataberkw** [comment]
> From reading this post: https://developer.apple.com/forums/thread/730974 this seems to be a new issue from mixing Xcode 15, with Flutter and having a iOS Home Widget added to the project. The fix that worked for me was from this:
> 
> > I was able to fix this by moving the Embed App Extensions, Embed Frameworks, and Embed Pods Frameworks to be performed before the Run Script build phase. I had just run into the issue in the Xcode 15.0 update and am building with Flutter w/ flavors.
> > ![image](https://private-user-images.githubusercontent.com/82344714/278280031-ea96e781-f9de-4f2c-9f13-2ee8b1504894.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODg1NTIsIm5iZiI6MTcwNzY4ODI1MiwicGF0aCI6Ii84MjM0NDcxNC8yNzgyODAwMzEtZWE5NmU3ODEtZjlkZS00ZjJjLTlmMTMtMmVlOGIxNTA0ODk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDIxNTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MmQzNmNiZjYzYzZhZGVkZTJjZWZkMGZiNWZjNTVlZDQ3Yjk1NWE2MDIzNzM2ZjFlZTdkODI5YmE5NmExYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2StNWuE8PesMEzTvgrXYRVnd304MbHx86WzCMmXtHz4)
> 
> Basically I moved all Build phases (from Runner -> Build Phases -> Targets -> Runner) that contained "Embedded" word before the first "Run Script" Can anyone else confirm this fixes the build process?
> 
> If everything is ok, maybe the README needs to be updated to include this fix.

This fixed my case too. Issue can be closed by updating the README. Also there can be an explanation why this problem occurs.
