### ISSUE TITLE
[Feature] HomeWidget.isSupported()

### ISSUE THREAD

**Issue by nielsbasjes** [ABausG/home_widget#174]
Because having a HomeWidget is only supported on certain platforms I propose a new function `bool HomeWidget.isSupported()` which simply returns if the current runtime of the application supports having a HomeWidget.

This wil make it easier for applications to know if the code fragments that build this widget is to be initialized/called.

I'm not 100% sure but I suspect the code can be as simple as this (perhaps even cache the value)

```dart
bool isSupported() {
  if (kIsWeb) {
    return false;
  }
  return (defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.android);
}
```

**Comment by ABausG** [comment]
I think this function should be build in each app as some people for example only build their widget for iOS so they might want to do some custom checking logic
