### ISSUE TITLE
await calls not working on iOS HomeWidget.registerInteractivityCallback while in background

### ISSUE THREAD

**Issue by bypass112** [ABausG/home_widget#176]
There seems to be an issue on iOS side when clicking the Home Widget button to refresh the data on the Home Screen Widget:

1. If you try to call a http get request from dart **@pragma("vm:entry-point")**, while having the app in the background and installed as Released on a physical device the http calls won't finish unless you bring the app manually to the foreground. Requests will work fine as long the app is running through XCode (and debugging) on the device
2.  An alternative would be to call 
`Workmanager().executeTask((task, inputData) async {
//API CALL HERE
return Future.value(true);
});`
from the home_widget 'backgroundCallback' set to respond from the home widget button call, but  it will fail and the app will just respond with 

> The 'home_widget/background' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method backgroundChannelInitialized on channel be.tramckrijte.workmanager/background_channel_work_manager)

Is there any way to fetch data from API REST calls using the new method of button clicks on the home widget for iOS?
Android is working fine with the current dart code that I have and is populating the widget UI elements fine from the http requests.

**Comment by bypass112** [comment]
It also seems that whatever the background method used for the `HomeWidget.registerInteractivityCallback` call, you can't add any await in it.
For example any code added after an `await Future.delayed(Duration(seconds: 3));` will not be executed, untill after the app is brought to the foreground.
This may not be an issue regarding http calls, but await calls.
Could someone help me find a solution for this please?

**Comment by mchudy** [comment]
Possible workaround is to start an iOS background task when executing the background callback (e.g. with this library https://pub.dev/packages/ui_background_task). I believe the problem is that the iOS can arbitrarily stop the execution of the Dart code when the app is in the background. Background task gives you 30 seconds to complete the operation.
