### ISSUE TITLE
Unresolved Reference: R

### ISSUE THREAD

**Issue by pikachupichu25** [ABausG/home_widget#177]
I have a flutter app and want to add a home screen widget to the app. My flutter code have two flavor settings for two apps with different application IDs. I want to add home screen widget only for one flavor.

When I compile, it always gets a runtime error. Unresolved reference: R at these two lines:

`val layoutId = R.layout.widget_layout`

`setTextViewText(R.id.appwidget_text, title ?: "No text set")`

This is my full file `android/app/src/main/kotlin/my/domain/app_name_flavor1/MyAppWidgetProvider.kt`

```
package my.domain.app_name_flavor1

import android.appwidget.AppWidgetManager
import android.content.Context
import android.content.SharedPreferences
import android.widget.RemoteViews
import my.domain.app_name_flavor1.HomeWidgetProvider


class MyAppWidgetProvider : HomeWidgetProvider() {

    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, 
                            appWidgetIds: IntArray, widgetData: SharedPreferences) {
        // TODO fix Unresolved reference: R error
        for (appWidgetId in appWidgetIds) {
            val widgetData = HomeWidgetPlugin.getData(context)
            val layoutId = R.layout.widget_layout
            val views = RemoteViews(context.packageName, layoutId).apply {

                val title = widgetData.getString("appwidget_text", null)
                // val title = "default"
                setTextViewText(R.id.appwidget_text, title ?: "No text set")
            }

            appWidgetManager.updateAppWidget(appWidgetId, views)


        }
    }
}

```

I try removing all code about R in this kotlin. The app has a static home screen widget as set in `android/app/src/flavor1/res/layout/widget_layout.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center"
    android:background="?android:attr/selectableItemBackground">

    <TextView
        android:id="@+id/appwidget_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@android:color/black"
        android:text="Hello World"
        android:textSize="24sp" />
</LinearLayout>

```

I try upgrade flutter, cleaning and rebuilding with `flutter clean` and `./gradlew clean.` None of those solves the issue.

What can I do to fix this error?

**Comment by offline-first** [comment]
Just open the android project folder with Android Studio (not the flutter project)

**Comment by pikachupichu25** [comment]
> Just open the android project folder with Android Studio (not the flutter project)

What does this mean? How does open it in Android Studio debug/resolve this error?

**Comment by offline-first** [comment]
@pikachupichu25 sorry for the late reply. This is just an IDE build error

**Comment by pikachupichu25** [comment]
@offline-first 
For my case, switching to Android Studio does not help. My error happens when I try to flutter run.
Then, the build is failed to build.

**Comment by offline-first** [comment]
@pikachupichu25 This error is related to Android Build Error. Open the android folder with Android Studio and get more insights after trying to build it. You cannot see the build errors with the logs of Flutter
