### ISSUE TITLE
ios 17 interactive widgets not execute action until app is opened

### ISSUE THREAD

**Issue by mpdevelopment39** [ABausG/home_widget#179]
First of all, **_thank u so much for your amazing work_** developing this incredible package :) 

I am implementing interactive widgets on iOS 17 in my app and I have a question about the implementation.

When I test on debug the widget works correctly when app is opened but not when app is killed and i don't know why :(

The action that i launch when button is clicked is only executed when app is opened from killed, but not automatically.

I implemented all the points that u mentioned in the Readme included this code:

`@available(iOS 16, *).` 
`@available(iOSApplicationExtension, unavailable).`
`extension BackgroundIntent: ForegroundContinuableIntent {}`

I would like to know what i need include or change in my native or dart code to make it work for me.

I have the feeling that it works only in debug mode and not in release mode but I have no way to test the debug mode with the app closed so I can't confirm it.

I look forward to hearing from you and thank you again.

**Comment by mpdevelopment39** [comment]
I've been testing more and I've noticed that sometimes the action does work correctly with the application closed, but it seems to be more a problem of not refreshing the widget interface or not executing the action when it should. This same thing was happening to me in the production Android app. It gives the feeling that the actions don't get to execute or refresh the widget until the app is opened again.

**Comment by mpdevelopment39** [comment]
### **_Last update:_**

I've seen this comment:

/// This is required if you want to have the widget be interactive even when the app is fully suspended.
/// Note that this will launch your App so on the Flutter side you should check for the current Lifecycle State before doing heavy tasks
@available(iOS 17, *)
@available(iOSApplicationExtension, unavailable)
extension BackgroundIntent: ForegroundContinuableIntent {}

And I have noticed that as you indicate, when I click on the widget button, invoking the intent to run my flutter code, when the app is closed, it opens with its normal flow but in the background. What I have been able to see is that the backgroundCallback is not executed in this case unless I click on the widget again after the first click. 

That is to say, with the app closed I press the widget button and it executes the main of my flutter app, it starts the app normally in the background but it doesn't execute the backgroundCallback automatically. Any idea why this could happen to me?

Thank you very much again.

**Comment by bypass112** [comment]
Hi, are you using any await calls? 
Can you please give a bit more info on your code lofig called by the button pressed on the Flutter side?
I've been having a similar issue with the new Button Widget in iOS 17 -> https://github.com/ABausG/home_widget/issues/176

**Comment by ABausG** [comment]
Could you please check again? This should be now fixed in 0.5.0
