### ISSUE TITLE
Interactive Widgets not working/crash iOS 17

### ISSUE THREAD

**Issue by PierreBresson** [ABausG/home_widget#180]
Hi,

I'm trying to use `HomeWidget.registerInteractivityCallback` but calling it triggers an crash in `SwiftHomeWidgetPlugin.swift` line 134 `let callbackHandels = call.arguments as! [Int64]`.

It sounds like it should be `let callbackHandels = call.arguments as! [Int64?]` as `callbackHandels[1]` is null in my case :
<img width="366" alt="Screenshot 2023-11-15 at 15 48 47" src="https://github.com/ABausG/home_widget/assets/8709134/7f8f176e-69a8-4446-904e-9e363f43d020">

I've tried to add the [workmanager lib](https://pub.dev/packages/workmanager) but it doesn't fix the issue. It's not clear if it's needed for interactive widgets as it's mentionned in Background Update, but since it adds support for headless execution maybe there is something I'm missing about the setup.

**Comment by ABausG** [comment]
Did you make sure that the method you are passing into `registerInteractiveCallback` is a static and public method?

**Comment by PierreBresson** [comment]
That was the issue. My method equivalent to the following : 
```
@pragma("vm:entry-point")
FutureOr<void> backgroundCallback(Uri data) async {
  // do something with data
  ...
}
```
was inside a widget. When I removed it and put in above my widget, then I don't have the crash anymore.
Thanks!
