### ISSUE TITLE
Exception "Receiver not registered" when exit app

### ISSUE THREAD

**Issue by huytower** [ABausG/home_widget#19]
Hello,

I only do one thing,
It is import your library and run app,
After I exit app manually,
I got exception immediately, as image in below : 

![Screen Shot 2021-04-13 at 15 09 31](https://user-images.githubusercontent.com/11640136/114520399-99298180-9c6b-11eb-9d91-46f474e26225.png)

In case I don't import your library, It's okay
![Screen Shot 2021-04-13 at 15 08 01](https://user-images.githubusercontent.com/11640136/114519536-b6118500-9c6a-11eb-9bc4-311c688ed729.png)

I'm sure this bug appear from previous version until latest version.
Please prevent this bug,

Thanks,
p/s : Please notice that I hasn't declare < receiver > tag in manifest xml yet_

I got these error logs : 

> D/AndroidRuntime(26991): Shutting down VM
E/AndroidRuntime(26991): FATAL EXCEPTION: main
E/AndroidRuntime(26991): java.lang.RuntimeException: Unable to destroy activity {.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: null
E/AndroidRuntime(26991): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4203)
E/AndroidRuntime(26991): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221)
E/AndroidRuntime(26991): 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
E/AndroidRuntime(26991): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
E/AndroidRuntime(26991): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26991): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(26991): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime(26991): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26991): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(26991): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/AndroidRuntime(26991): Caused by: java.lang.IllegalArgumentException: Receiver not registered: null
E/AndroidRuntime(26991): 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1007)
E/AndroidRuntime(26991): 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1330)
E/AndroidRuntime(26991): 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
E/AndroidRuntime(26991): 	at es.antonborri.home_widget.HomeWidgetPlugin.onDetachedFromActivity(HomeWidgetPlugin.kt:150)
E/AndroidRuntime(26991): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:389)
E/AndroidRuntime(26991): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:560)
E/AndroidRuntime(26991): 	at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:595)
E/AndroidRuntime(26991): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:616)
E/AndroidRuntime(26991): 	at android.app.Activity.performDestroy(Activity.java:6881)
E/AndroidRuntime(26991): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
E/AndroidRuntime(26991): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190)
E/AndroidRuntime(26991): 	... 9 more

> [✓] Flutter (Channel master, 2.2.0-11.0.pre.69, on macOS 11.2.3 20D91
>     darwin-x64, locale en-VN)
>     • Flutter version 2.2.0-11.0.pre.69 at /Users/huytd/flutter
>     • Framework revision 02efffc134 (5 days ago), 2021-04-10 03:49:01 -0400
>     • Engine revision 8863afff16
>     • Dart version 2.13.0 (build 2.13.0-222.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/huytd/android-sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = /Users/huytd/android-sdk
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.4, Build version 12D4e
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
> 
> • No issues found!

**Comment by yasseralhendawy** [comment]
Same issue here

**Comment by ABausG** [comment]
I think I know where this is coming from and think I know how to fix it. However before I want to make sure that it is properly fixed. Can you provide more information on the setup on how to reproduce it?

Especially:
- Flutter Version
- Android Version

**Comment by huytower** [comment]
I updated `flutter doctor -v` in first comment already.

**Comment by ABausG** [comment]
Fixed in `0.1.2+1`

**Comment by theBlbDan** [comment]
I just wanted to drop a note and say thank you so much for finding the issue and resolving it.  I don't use home_widget, but I recently added ACRA to my project, which required creating a class that extended ```Application``` and as such, my calls to ```.finish()``` or ```.recreate()``` were causing a crash in my ```Activity.onDestroy()``` where I unregister my ```BroadcastReceiver```

Seeing your commit https://github.com/ABausG/home_widget/commit/4f692310883a1bc1aeebb4c79af54b25b2bc4905, it became so obvious as to why it was occurring.  The context for ```unregisterReceiver()``` had shifted from my Activity to my Application, which isn't who registered the receiver to begin with.

So, thank you.
