### ISSUE TITLE
home_widget not working after updating to flutter 3.16

### ISSUE THREAD

**Issue by PierreBresson** [ABausG/home_widget#190]
After updating to flutter 3.16.2, inside `SwiftHomeWidgetPlugin.swift` I get the following error on registrar.addApplicationDelegate(instance) : 
`'addApplicationDelegate' is unavailable in application extensions for iOS: Disallowed in plugins used in app extensions`

**Comment by ABausG** [comment]
This is now fixed in Version 0.5.0
