### ISSUE TITLE
renderFlutterWidget does not render the images inside my widget

### ISSUE THREAD

**Issue by moaud** [ABausG/home_widget#195]
renderFlutterWidget does not render the images inside my widget (first image ) but it works if I use another way to generate the screenshot like Davinci (second image )
![Screenshot 2023-12-23 221929](https://github.com/ABausG/home_widget/assets/16393083/d79522b9-5196-4a48-9144-efb4ca6ee6ac)
![Screenshot 2023-12-23 222256](https://github.com/ABausG/home_widget/assets/16393083/43cdd455-f887-4b8a-99a7-5e57e7629a5e)

**Comment by muhammadCodeSh** [comment]
same bug

**Comment by ABausG** [comment]
Closing as duplicate of #178
