### ISSUE TITLE
Drop connection between method channel of native code and flutter 

### ISSUE THREAD

**Issue by Atevaz** [ABausG/home_widget#196]
In first i need to thank you about this great job of the package but i have a problem
A problem in interaction in home widget
I take action in home widget like the example in your repository
When i click in title the title is change to other title the problem appears when i click more the 10 times the connection is pause and return after two minutes or more 
The widget is pause and play after two minutes or more 
I need to two the reason of the problem
Thanks .

**Comment by ABausG** [comment]
Yes iOS limits how often the widget can be updated to optimize performance/battery of the devices.
