### ISSUE TITLE
Periodical update from background on Android 13 does not work as expected

### ISSUE THREAD

**Issue by mkulesh** [ABausG/home_widget#198]
I would like to use your fantastic package in my app (https://github.com/mkulesh/onpc/tree/onpc-flutter) and tried your example (https://github.com/ABausG/home_widget/tree/main/example) on Motorola G52 (Android 13). Unfortunately I am not able to get a periodical widget update from background working. My configuration:
```
[!] Flutter (Channel [user-branch], 3.16.0, on Fedora Linux 35 (Workstation Edition) 6.0.5-100.fc35.x86_64, locale en_US.UTF-8)
    ! Flutter version 3.16.0 on channel [user-branch] at /work/android/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision db7ef5bf9f (6 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /work/android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /work/android/sdk
    • ANDROID_SDK_ROOT = /work/android/sdk
    • Java binary at: /work/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1 (Fedora 13.0.1-1.fc35)
    • cmake version 3.22.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.2)
    • Android Studio at /work/android/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • moto g52 (mobile) • ZY22FMC4SB • android-arm64 • Android 13 (API 33)
    • Linux (desktop)   • linux      • linux-x64     • Fedora Linux 35 (Workstation Edition) 6.0.5-100.fc35.x86_64

[✓] Network resources
    • All expected network resources are available.
```

Steps to reproduce the problem:
- Download https://github.com/ABausG/home_widget and import example into Android Studio
- Edit pubspec.yaml and replace dependencies by
```
dependencies:
  flutter:
    sdk: flutter
  workmanager: ^0.5.1
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  path_provider_foundation: ^2.3.1
  home_widget: ^0.4.1
```
- Change the method callbackDispatcher in order to show seconds as follows:
```
      HomeWidget.saveWidgetData(
        'message',
        '${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}:${now.second.toString().padLeft(2, '0')}',
      ),
```
- Change the method _startBackgroundUpdate in order to increase update frequency as follows:
```
  void _startBackgroundUpdate() {
    Workmanager().registerPeriodicTask(
      '1',
      'widgetBackgroundUpdate',
      frequency: const Duration(seconds: 1),
    );
  }
```
- Run example application in RELEASE mode
*Observer behavior*: app compiled, installed and started successfully. It is as desired.
- Close the app and add widget on the home screen. Resize widget.
*Observer behavior*: widget installed successfully. It is as desired.
![Screenshot_20231226-132137](https://github.com/ABausG/home_widget/assets/30557348/d4778982-c95f-4c69-a81e-3f56afd97144)
- Press on the widget
*Observer behavior*: the app started, message "App started from HomeScreenWidget" appears. It is as desired.
- Press "Update in background" button and close the app
*Note*: following log appears in the Android Studio:
```
W/FlutterJNI( 7446): FlutterJNI.loadLibrary called more than once
W/FlutterJNI( 7446): FlutterJNI.prefetchDefaultFontManager called more than once
W/FlutterJNI( 7446): FlutterJNI.init called more than once
```
Is is a desired behavior?
*Observer behavior*: the widget is updated that is as desired.
- Wait a minute
*Observer behavior*: the widget is *not* updated, the indicated time is obsolete, the seconds are not changed. It is *not* as desired:
![Screenshot_20231226-134444](https://github.com/ABausG/home_widget/assets/30557348/1dc5f5b9-0c96-458d-8369-c95bbe6e1267)
- Press on the widget title
*Observer behavior*: the title is changed that is as desired.
- Press on the widget again. When app started, press "Update in background" button and close the app
*Observer behavior*: the widget is *not* updated, the indicated time is obsolete. it is *not* as desired
![Screenshot_20231226-134558](https://github.com/ABausG/home_widget/assets/30557348/d1156671-a102-44b7-85c8-15af8714d566)

How can I get background widget update working with the update rate equal to 1 sec?

**Comment by ABausG** [comment]
There are limits how often you can update the widgets.
I believe Android suggests to limit updates to as little as possible (2-3 times per hour)

If you need to display a timer you can use something like this: https://stackoverflow.com/a/72978180
