### ISSUE TITLE
Support more data types

### ISSUE THREAD

**Issue by ABausG** [ABausG/home_widget#2]

**Comment by aytunch** [comment]
@ABausG can we send Images from dart as Home widgets? Or are we limited with Strings and Urls?

**Comment by ABausG** [comment]
RAW Images are not possible. I guess you could play around with converting an image to a base64 string and use that to transport the data between your app and the widget

**Comment by aytunch** [comment]
I was thinking of converting an UI widget to an Image and send with your plugin. Do you think the performance would be OK if I convert the Image data to a base64 string and send it this way? An example would be superb if you ever have the time.
Thanks.

**Comment by adrianvintu** [comment]
@aytunch why not save the file locally in Dart and sent the string path to the Java/Swift code to load the file?

**Comment by aytunch** [comment]
@adrianvintu if that works, I think it could be much easier and performant than converting the image to base64. I hope this solution can be embedded to this plugin.

**Comment by adrianvintu** [comment]
@aytunch this has nothing to do with the plugin, this is something you need to code.
