### ISSUE TITLE
Exception: Failed to save screenshot to app group container: PathAccessException: Creation failed, path = 'null'

### ISSUE THREAD

**Issue by ThuyenPV** [ABausG/home_widget#200]
Unhandled Exception: Exception: Failed to render the widget: Exception: Failed to save screenshot to app group container: PathAccessException: Creation failed, path = 'null' (OS Error: Operation not permitted, errno = 1)
#0      HomeWidget.renderFlutterWidget (package:home_widget/home_widget.dart:236:7)
<asynchronous suspension>
#1      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#2      _MyAppState._sendAndUpdate (package:home_widget_example/main.dart:143:5)

**Comment by ABausG** [comment]
Which Version of home_widget are you using and on which Platform?

**Comment by thanhtung0316** [comment]
I'm facing the same problem on IOS, home_widget: ^0.4.1, ios 16.2, flutter 3.10.6 @ABausG, please take a look.

**Comment by sikandernoori** [comment]
Same issue on IOS, version 0.5.0

**Comment by sikandernoori** [comment]
Forgot to add group_ID, that was a fix for this issue.
