### ISSUE TITLE
 Swift Compiler Error (Xcode): 'addApplicationDelegate' is unavailable in application extensions for iOS

### ISSUE THREAD

**Issue by ThuyenPV** [ABausG/home_widget#201]
Could not build the precompiled application for the device. Swift Compiler Error (Xcode): 'addApplicationDelegate' is unavailable in application extensions for iOS: Disallowed in plugins used in app extensions /Users/thupv2/thupv/research/home_widget/ios/Classes/SwiftHomeWidget Plugin.swift:32:14    Error launching application on Thuyen Pham Iphone.

**Comment by rohanots** [comment]
Getting the same issue. Any fix yet?
![image](https://github.com/ABausG/home_widget/assets/86669706/2cd4599b-2152-4f8e-b16b-517ab1ff7149)

**Comment by ABausG** [comment]
Can you please let me know some Infos:

- Flutter Doctor Output
- XCode Version
- iOS Deployment Versions

**Comment by ABausG** [comment]
Update on this: Found the culprit and noticed this happens when adding interactivity to iOS Widgets (and including the Library in the Pods for the Extension)

I am working on a fix for this

**Comment by armandsLa** [comment]
Running in same issue. Replacing `pod 'home_widget', :path => '.symlinks/plugins/home_widget/ios'` with `inherit! :search_paths` in `Podfile` seems to fix the issue.

**Comment by ataberkw** [comment]
> Running into same issue. Replacing `pod 'home_widget', :path => '.symlinks/plugins/home_widget/ios'` with `inherit! :search_paths` in `Podfile` seems to fix the issue.

This does not fixes the issue. As the author mentioned, adding interactivity is the culprit. When you apply your workaround, you won't be able to `import home_widget`. This is just a workaround for people don't want to use interactivity. Not a fix.

**Comment by armandsLa** [comment]
It's a workaround, yes, but it allows you to import the home_widget and implement interactivity. I've just done that in my app without any issues. If interactivity is not needed, then there is no reason to include home_widget in your extension target at all.

**Comment by armandsLa** [comment]
Inheriting search paths worked fine until it didn't. I've created a PR with a fix that allows importing `home_widget` in widget extension. Feel free to use my branch until this or other fix gets merged.

PR: https://github.com/ABausG/home_widget/pull/228

**Comment by ataberkw** [comment]
> It's a workaround, yes, but it allows you to import the `home_widget` and implement interactivity. I've just done that in my app without any issues. If interactivity is not needed, then there is no reason to include `home_widget` in your extension target at all.

You were right. I guess I confused something because I tried to apply tons of workaround to fix this issue. I'm using your workaround and `isSetupCompleted = true;` patch in `setupEngine` for 2 weeks without a problem. Also thanks for your efforts on pull request.

Now I realized you made pull request for [ignoreSetup](https://github.com/ABausG/home_widget/issues/219#issuecomment-1942017761) 🚀🚀🚀

**Comment by ABausG** [comment]
Fixed in Version 0.5.0
