### ISSUE TITLE
I want to automatically update widgets every once in a while, can this plug-in be used in a production environment?

### ISSUE THREAD

**Issue by GanZhiXiong** [ABausG/home_widget#202]
This is a great plugin.

## Requirement
Implement a widget that supports **Android and iOS.**
I want to use it and flutter_workmanager to request the HTTP interface to update the data on the widget every 15 minutes.

## Question
But it now has 58 Issues and flutter_workmanager now has 76 Issues, which worries me.
Can I use this plug-in to implement my needs in a **production environment**?

**Comment by GanZhiXiong** [comment]
I am now deciding whether to implement this requirement natively or with this plugin？

**Comment by ABausG** [comment]
Yes this plugin is used by various apps in production.
