### ISSUE TITLE
[iOS] So far, only UserDefault can be used to share data with the main runner?

### ISSUE THREAD

**Issue by BenderBlog** [ABausG/home_widget#206]
Just curious, not bug. This plugin is awesome!

To be clear, a Swift beginner...

In Apple devices, we have to use `groupid` to share data between the main app and HomeWidget, UserDefault is used in this plugin. My data is too huge (related to schedule data, about 10kb), maybe too huge to put it in the UserDefault. Although I use `background_fetch` to update the plugin every 15 minute, somebody said that it may be killed sometimes. Don't know whether it is true, but I was thinking, could I read data from the main app, via groupid?

Since groupid is used, I tried to use an alternative way, by reading the shared data folder:

```swift
let appSupportURL = FileManager().containerURL(forSecurityApplicationGroupIdentifier: widgetGroupId)!
```

By the way, the data I read is stored in `Application Support Directory` as defined by `path_provider` plugin. And unfortunately, it failed, saying that these two folder is not the same.  `Application Support Directory` means the private main runner data, it seems...

![e8a1e572f0d65edc960064389bbec785](https://github.com/ABausG/home_widget/assets/14026321/f5c9d49c-8479-4c55-bf73-2d08a2517301)

So, is there anyway to store data to the shared folder in the main runner, the Flutter code? I mean, since groupid provided...

**Comment by ABausG** [comment]
Yes home_widget only supports syncing data via UserDefaults. If you need other logic unfortunately this goes beyond the (current) support of home_widget. I am not sure if there are other ways of accessing data from the home widget itself as I believe they are sandboxed differently.

Would love to hear if you find a way but as mentioned this is out of scope of home_widget. (If you send data in another way you should still be able to use home_widget to update the widget)
