### ISSUE TITLE
[Android] HomeWidgetLaunchIntent causing MaterialApp to relaunch home widget when app backgrounded

### ISSUE THREAD

**Issue by craigspicer** [ABausG/home_widget#208]
Flutter version: 3.16.7
home_widget version: 0.4.1
compiling and targeting API level: 34

I've used this package for a long time with no issues but since updating to the latest version of Flutter whenever I click on a button on my home screen widget that creates a pending intent, a new instance of my MaterialApp home widget is launched. This only happens when the app is backgrounded. It works as expected when launching the app from a closed by clicking a button on the home screen widget.

Nothing has been changed in kt or dart code.

Please let me know what additional information you may need. Thank you.

**Comment by ABausG** [comment]
You need to adjust the launchMode of your activity: https://developer.android.com/guide/topics/manifest/activity-element
to something like `singleTask`

**Comment by craigspicer** [comment]
I've always had it set to singleTask and it still is. It always worked perfectly until updating to Flutter 3.16.

**Comment by khjde1207** [comment]
android/app/src/main/AndroidManifest.xml
```
 <activity
            android:name=".MainActivity" 
...>
...
  <meta-data android:name="flutter_deeplinking_enabled" android:value="false" />
...

</activity> 
```
