### ISSUE TITLE
Issue updating widget when using IntentTimelineProvider

### ISSUE THREAD

**Issue by Tedsterh** [ABausG/home_widget#21]
I have a fully working IntentTimelineProvider that allows me to choose content for the widget to show from inside my flutter application. This works great.

The only issue is I can no longer seem to update the widget using `HomeWidget.update` am I missing something or is this a limitation?

**Comment by ABausG** [comment]
Could you provide some example code? I'm not an iOS Expert but from what I read it you should be able to use it in combination with `HomeWidget.update`

`HomeWidget.update` is updating the widget based on the `kind` of the widget

**Comment by Tedsterh** [comment]
`func getTimeline(for configuration: ConfigurationIntent, in context: Context, completion: @escaping (Timeline<Entry>) -> ()) {
        let data = UserDefaults.init(suiteName:widgetGroupId)
        var entries: [SimpleEntry] = []
        
        var hasData = false
        
        var ids = WidgetData(name: "Unknown", color: "Green", widgetId: "Unknown", ids: [])
        
        var content: Array<Data> = []
        

        if configuration.widgetType?.widgetID != nil {
            let newData = data?.string(forKey: (configuration.widgetType?.widgetID!)!)?.data(using: .utf8)!
            
            let decoder = JSONDecoder()
            
            let json = """
            {
            }
            """.data(using: .utf8)!
            
            do {
                let widget = try decoder.decode(WidgetData.self, from: newData ?? json)

                if (widget.name != nil) {
                    ids = widget
                    hasData = true
                } else {
                    ids = WidgetData(name: "Unknown", color: "Green", widgetId: "Unknown", ids: [])
                    hasData = false
                }
            } catch {
                print(error)
            }
            
            for id in (ids.ids ?? []) {
                let widgetData = data?.string(forKey: (id!))?.data(using: .utf8)!
                
                do {
                    var mappedWidgetData = try decoder.decode(Data.self, from: widgetData ?? json)
                    
                    if (mappedWidgetData.type == 0) {
                        mappedWidgetData = try decoder.decode(Pomodoro.self, from: widgetData ?? json)
                        
                        if (mappedWidgetData is Pomodoro) {
                            let pomodoro: Pomodoro = mappedWidgetData as! Pomodoro
                            
                            mappedWidgetData = Pomodoro(id: pomodoro.id, type: pomodoro.type, running: pomodoro.running, paused: pomodoro.paused, onBreak: pomodoro.onBreak, taskName: pomodoro.taskName, endTime: pomodoro.endTime, remaining: pomodoro.remaining ?? buildIt(interval: pomodoro.endTime ?? 0), breakCount: pomodoro.breakCount)
                        }
                    }
                    
                    content.append(mappedWidgetData)
                } catch {
                    print(error)
                }
            }
        }

        let  entryDate = Calendar.current.date(byAdding: .second, value: 1 , to: Date())!
                     let entry = SimpleEntry(date: entryDate, title: data?.string(forKey: "title") ?? "No Title Set", hasData: hasData, widgetData: ids, size: context.family.rawValue, content: content)
              
                    entries.append(entry)
                   
                    let timeline = Timeline(entries: entries, policy: .after(entryDate))
        var timer = Timer()
        timer =  Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { (timer) in
                    WidgetCenter.shared.reloadAllTimelines()
            completion(timeline)
        }
    }`

This is what I currently have in my `getTimeline` function, am I receiving all the app data perfectly so my appGroup ID is working and the correct value.
