### ISSUE TITLE
not work in release mode

### ISSUE THREAD

**Issue by linkaituo** [ABausG/home_widget#211]
hey, ths a lot for the amathing package.
i use home_widget in debug mode in ios17+, it work well, can interactive with button.
but when i use in release mode, can't interactive.
any maybe problem?

**Comment by kreazyme** [comment]
Pls provide some information like platform, version, your code...
You can re-check your application ID (cause flavor...)

**Comment by ABausG** [comment]
Did you make sure that you added the `appGroup` capability also to the release config for both the App and the extension?
