### ISSUE TITLE
Widget Becoming Unresponsive after 10-12 clicks on button which increments the value on the widget

### ISSUE THREAD

**Issue by navaneethku** [ABausG/home_widget#213]
Widget Becoming Unresponsive after 10-12 clicks on button which increments the value on the widget. It becomes normal after a while until a similar amount of clicks are done. I faced this issue with the implementation by myself and one another video from YouTube, hoping that there is a fix, or is it some kind of limitation for an android widget?

The youtube link: https://www.youtube.com/watch?v=VqdYKNj_3bw
His repo link: https://github.com/nbnD/app_widget

**Comment by ABausG** [comment]
Yes the Operating system limits how often widgets can be updated. After some time everything should get back to normal
