### ISSUE TITLE
Can I display the FCM message on the widget?

### ISSUE THREAD

**Issue by GanZhiXiong** [ABausG/home_widget#216]
We want to update the widget in time, but since the update frequency of the widget is limited to at least 15 minutes, I want to display the mobile phone's message push on the widget.

**Comment by ABausG** [comment]
It should be possible. Please have a look at this section https://github.com/ABausG/home_widget?tab=readme-ov-file#background-update

I believe it should not make a difference if you use Workmanager or FCM to trigger Widget Changes while the app is in the background. Please note that you might need to ensure that the FCM Plugin has the ability to register other plugins (home_widget) in this case
