### ISSUE TITLE
iOS Interactive Button Action not sent to App (HomeWidgetBackgroundWorker isSetupComplete always false)

### ISSUE THREAD

**Issue by lora-explora** [ABausG/home_widget#219]
Hi, I just implemented the interactive functionality, where I increase a value that is displayed in my app(s).
Everything works well in Android, but for some reason the iOS action does not.

I noticed that:
- I need to run the app on my device and not on the simulator, otherwise the perform() method of the AppIntent will not be called at all. Is this normal behaviour? If so, it could be added to the Readme for others.
- In the HomeWidgetBackgroundWorker.run() method isSetupCompleted is always false, therefore my events are always appended to the queue. 

I am happy for any pointer in the right direction!
Let me know if you need further info.

**Comment by Codestian** [comment]
I also experienced the same problem. My current solution is to directly go to the source code for home_widget and set the isSetupComplete variable to true right before the codes in the method. So far no issues, on both simulator and physical device, and after reboots.

**Comment by lora-explora** [comment]
Aaah thanks!! This helped me figure it out. I for once dug a bit deeper and realised that I hadn't set the appGroupID in my dart code before registering the interactive callback 🤦 Therefore it really wasn't setup..
And I added "isSetupCompleted = true" to the end of the setupEngine method in the HomeWidgetBackgroundWorker.

**Comment by armandsLa** [comment]
I created a fork with an option flag `ignoreSetup` added to the `HomeWidgetBackgroundWorker.run` method.

Use it like this: `await HomeWidgetBackgroundWorker.run(url: _url, appGroup: Common.suiteName, ignoreSetup: true)`

Update pubspec.yaml:
```
  home_widget:
    git:
      url: https://github.com/armandsLa/home_widget.git
      ref: main
```

**Comment by ABausG** [comment]
Hey all! Is it really that the setup never completes?
Are you running into these issues all the time? Or only when the App is/isn't opened in the background?

**Comment by armandsLa** [comment]
Yes, the `isSetupCompleted` flag is always false on iOS. This is likely because it can only be set to `true` by adding an interactivity callback, but that occurs in the app's main process, not in the widget extension. Memory between these processes is not shared.

**Comment by armandsLa** [comment]
I've noticed that sometimes, when I try to perform an action in a widget, it doesn't go through. This usually happens after a longer period of inactivity. The first action receives no response, but the second works as it should. I suspect this is due to the removal of `isSetupCompleted`, which checked if the platform channel was initialized and placed the action in a queue if it wasn't. It shouldn't be a gesture issue, as I can see the button changing its state.

**Comment by armandsLa** [comment]
Here is a PR with a proper fix: https://github.com/ABausG/home_widget/pull/229
