### ISSUE TITLE
Widget won't update after exit the app

### ISSUE THREAD

**Issue by EarbajEvidentBD** [ABausG/home_widget#234]
widget won't update after exit the app and need periodic update while app on background suppose we add timer to app as long as the timer running the widget should update and show the timer value if app on the background

**Comment by ABausG** [comment]
You should look into something like Workmanager to perform a task like this.
Also on iOS you can use the timeline functionality to pre configure certain updates at specific times.

If you want to display a running timer there are special widgets for iOS and Android https://stackoverflow.com/a/66260818
