### ISSUE TITLE
[iOS] I'd like to get the widgetURL from each button in .systemMedium.

### ISSUE THREAD

**Issue by ttb-inc** [ABausG/home_widget#235]
Hi

I'm applying the home_widget package to iOS.
I'm getting the widgetURL just as I want.

I'd like to get the widgetURL from each button in .systemMedium.
Is there a way to do this?

```swift
var body: some View {
        switch family {
        case .systemMedium:
            HStack(content: {
                Spacer()

                Image(SimpleEntry.imageRunApp)
                    .resizable()
                    .scaledToFill()
                    .frame(width: iconSize, height: iconSize)
                    .widgetURL(URL(string: "myapp://?homeWidget&click=0"))
                
                Spacer()
                
                Image(SimpleEntry.imageQRCodeScan)
                    .resizable()
                    .scaledToFill()
                    .frame(width: iconSize, height: iconSize)
                    .widgetURL(URL(string: "myapp://?homeWidget&click=1"))
                
                Spacer()
            })
        default:
            Text("Null View")
        }
    }
```

With the above code, only "myapp://?homeWidget&click=1" is always passed.
I want them to be passed separately.

Thank you.

**Comment by ABausG** [comment]
Looks like you need a Link as only one widgetUrl is being used.

https://stackoverflow.com/a/76452233

Could you check if home_widget works with a Link? I never tested that

**Comment by ttb-inc** [comment]
> Looks like you need a Link as only one widgetUrl is being used.
> 
> https://stackoverflow.com/a/76452233
> 
> Could you check if home_widget works with a Link? I never tested that


Thank you for your quick response.

It works so, so, so well.
Great!!!
Thank you so much.

Have a good one.

**Comment by ABausG** [comment]
@ttb-inc If you have the time would you mind adding this to the README?

Glad that it worked

**Comment by ttb-inc** [comment]
> @ttb-inc If you have the time would you mind adding this to the README?
> 
> Glad that it worked

Thank you.

Of course I should, but English is not my first language.
I'm really sorry about that. 😥🙏🙏🙏
I'll be sure to PR anything related to the code.
