### ISSUE TITLE
InteractivityCallback called only after restart on iOS

### ISSUE THREAD

**Issue by MichaelLucca** [ABausG/home_widget#236]
**Description**
Following the specified steps, I implemented a Widget in iOS with a Button that calls an interactivityCallback defined in Dart.

The issue is that upon the initial launch of the app, interacting with the widget does not trigger the method. However, upon returning to the app and performing a refresh, it appears the method has been called every time, as if it were cached somewhere in memory.

**Comment by ABausG** [comment]
Yes. This will known and should be fixed in the next release thanks to #229
