### ISSUE TITLE
Not able to navigate to another screen in a flutter on tap of the home widget.

### ISSUE THREAD

**Issue by ashwaniRoshan** [ABausG/home_widget#242]
I'm encountering difficulty in implementing screen navigation within a Flutter app when tapping on a home widget. Despite configuring the widget to respond to taps and trigger navigation to another screen, the expected behavior of navigating to the desired screen is not occurring.

Expectation:
I expected that upon clicking the profile button within the widget, the app would navigate users to the app's profile screen. Additionally, I anticipated being able to pass data along with the navigation request to determine which screen to navigate to.

Outcome:
However, the implemented code only results in opening the app when the profile button is clicked. I haven't found a way to pass any type of data with the navigation request, making it challenging to determine the destination screen for navigation.

`val pendingIntent = HomeWidgetLaunchIntent.getActivity(
    context,
    MainActivity::class.java
)

setOnClickPendingIntent(R.id.btnProfile, pendingIntent)`

**Comment by Ayush783** [comment]
I don't think you read the docs
https://github.com/ABausG/home_widget?tab=readme-ov-file#launch-app-and-detect-which-widget-was-clicked

specify URI in your pending intent
