### ISSUE TITLE
spoiling 48 hours configuring the **** gradle versions. desperated.

### ISSUE THREAD

**Issue by StaticReasons** [ABausG/home_widget#243]
never gonna use it.
unless anyone could tell me in 2077 this package can be imported without errors within less than 5 commands.

what sort of **** packaging system need us to use our own neurons to resolve these dependency matters?

**Comment by binhtran93** [comment]
I could not either, using the latest flutter, could not build the project. Please someone look at this

**Comment by ABausG** [comment]
Please stay on topic. This is afterall something I do in my free time. How do you think I could help you with the information you provided?

Check out the example App's Gradle configuration page or the example here: https://github.com/ABausG/home_widget_counter
