### ISSUE TITLE
[Missing Plugin exception] Interactive widget buttons are not able to initialise the plugins and packages on iOS when the app is killed/background. 

### ISSUE THREAD

**Issue by rohanots** [ABausG/home_widget#255]
Posted this issue on the flutter blue plus library. Check here for the detailed query.
[https://github.com/boskokg/flutter_blue_plus/issues/861#issuecomment-2076493681](url)

I am trying to run a bluetooth scan and connection request when pressing the home widget button on iOS.

**Comment by ABausG** [comment]
Did you register the plugin registrar so that home_widget knows which plugins to instantiate

```swift
    if #available(iOS 17, *) {
      HomeWidgetBackgroundWorker.setPluginRegistrantCallback { registry in
        GeneratedPluginRegistrant.register(with: registry)
      }
    }
```
