### ISSUE TITLE
Flutter 2.22: No named parameter with the name 'size

### ISSUE THREAD

**Issue by g-apparence** [ABausG/home_widget#257]
The new flutter version has removed size from the ViewConfiguration resulting in this error: 
`home_widget.dart:176:11: Error: No named parameter with the name 'size'.`

Here is the new code
```
const ViewConfiguration({
    this.physicalConstraints = const BoxConstraints(maxWidth: 0, maxHeight: 0),
    this.logicalConstraints = const BoxConstraints(maxWidth: 0, maxHeight: 0),
    this.devicePixelRatio = 1.0,
  });
```

So home_widget size should be updated with logical constraints
```dart
final RenderView renderView = RenderView(
        view: ui.PlatformDispatcher.instance.implicitView!,
        child: RenderPositionedBox(
          alignment: Alignment.center,
          child: repaintBoundary,
        ),
        configuration: ViewConfiguration(
          size: logicalSize,
          devicePixelRatio: 1.0,
        ),
      );
```

**Comment by ABausG** [comment]
What version of home_widget are you on? Version 0.6.0 should address this change (comes from branch flutter-beta in here but already lived on pub.dev as a pre release)

**Comment by g-apparence** [comment]
@ABausG ah sorry didn't see that version 0.6.0 was ready. 
I close this then. 

PS : good job doing this 👌
