### ISSUE TITLE
'updateWidget' in Android doesn't end the method call

### ISSUE THREAD

**Issue by ajinasokan** [ABausG/home_widget#26]
In [HomeWidgetPlugin.kt#L79](https://github.com/ABausG/home_widget/blob/main/android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetPlugin.kt#L79) a call to `result.success` is missing. 

So when you await updateWidget like below it doesn't finish.

```dart
await HomeWidget.updateWidget(
    name: 'WidgetProvider',
    androidName: 'WidgetProvider',
    iOSName: 'WidgetProvider',
);
```

I haven't personally tested this. If you prefer, I can test and send a PR.

**Comment by ABausG** [comment]
Thanks for the report. Will be fixed in the next version

**Comment by KuoyHuot** [comment]
The updateWidget doesn't finish on ios for me. It seems to be missing, too.
