### ISSUE TITLE
Question: Can widget audo refresh to get new data

### ISSUE THREAD

**Issue by jonaskahn** [ABausG/home_widget#260]
First time enter here, I just wonder can widget auto refresh ?

**Comment by hyzhan43** [comment]
same question

**Comment by jonaskahn** [comment]
I saw in demo, he provide a small button for user fetch data, but it would be great if autorefresh is supported

**Comment by ABausG** [comment]
https://github.com/ABausG/home_widget?tab=readme-ov-file#background-update

Some notes on this:
In the Example there is a guide how to use workmanager to trigger background updates (at least on android) the same logic applies for other means of updating the app scheduled.

If you already know when you want to update the widget with predefined data you can also schedule this on the native site e.g on iOS using dedicated timeline entries.

As the methods are static you are also able to update the widget from other Background Methods (e.g Background Pushes) as long as the Plugin gets registered. I hope this answers the question.
