### ISSUE TITLE
saveWidgetData issue

### ISSUE THREAD

**Issue by roderikpeeters** [ABausG/home_widget#261]
With the saveWidgetData I have the issue that the String is changing locally (if I use the getter after it in my logs, it prints the correct one). But my widget isnt being updated.

I also tried creating new dummy widgets to see what happens if I create a new simple widget
But Im unable to edit my widget text by clicking on a button with savewidgetdata and updatewidget in it.

Any possible steps to troubleshoot this?

**Comment by ABausG** [comment]
Not entirely sure what you are trying to achieve. Did you check this article about interactivity:

https://medium.com/@ABausG/interactive-homescreen-widgets-with-flutter-using-home-widget-83cb0706a417

Remember that when you change data you need to update the widget as well.

Closing this for now
