### ISSUE TITLE
'import es.antonborri.home_widget.HomeWidgetBackgroundReceiver' throwing error.

### ISSUE THREAD

**Issue by gaurovgiri** [ABausG/home_widget#262]
I was following the [CodeLabs](https://codelabs.developers/google.com/flutter-home-screen-widgets). When I tried to run the app after completing the 4 slide! It threw error about the ViewConfiguration(). After looking through closed issues, I was able to tackle it through using`0.6.0` version and also used Flutter `3.2.xx Beta`. But after that I'm getting this issue!
<img width="1096" alt="Screenshot 2024-06-02 at 11 09 50 PM" src="https://github.com/ABausG/home_widget/assets/64427471/473fb966-04c1-41ea-b67f-93c65d11af78">
<img width="902" alt="Screenshot 2024-06-02 at 11 09 24 PM" src="https://github.com/ABausG/home_widget/assets/64427471/2669549b-916a-4468-af5a-1d26b640ac17">

I also tried using:
```
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (11 days ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3
```

**Comment by ABausG** [comment]
Not sure how you ended up with the code at those lines. They should look like this:

https://github.com/ABausG/home_widget/blob/365f8f910bccf577b0103a239d26d8e3c175e06e/android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetIntent.kt#L51-L54
