### ISSUE TITLE
HomeWidget.updateWidget invalid type error message for Long

### ISSUE THREAD

**Issue by bannzai** [ABausG/home_widget#269]
## Abstraction
I got error message when running android app and call `HomeWidget.updateWidget` with `Long` value. 

## Message
`PlatformException(-10, Invalid Type Long. Supported types are Boolean, Float, String, Double, Long, java.lang.IllegalArgumentException`

## Issue
This message has `Invalid Type Long` and `Supported types are ... Long`. So, I confused. Please check it. Thank you.

**Comment by bannzai** [comment]
FYI: https://github.com/ABausG/home_widget/blob/365f8f910bccf577b0103a239d26d8e3c175e06e/android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetPlugin.kt#L56

I guess wrong anything arround the line.

**Comment by alpha2048** [comment]
Same problem here.
