### ISSUE TITLE
The named parameter 'size' isn't defined.

### ISSUE THREAD

**Issue by bannzai** [ABausG/home_widget#271]
I got error when build with flutter 3.22.2. 

Full message: `The named parameter 'size' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'size'`

Flutter 3.22.2, doesn't have `size` parameter of ViewConfigurations.
ref: https://github.com/ABausG/home_widget/blob/main/lib/src/home_widget.dart#L176

**Comment by ABausG** [comment]
Please upgrade to home_widget 0.6.0
