### ISSUE TITLE
Possibility to update style of widget

### ISSUE THREAD

**Issue by jkbngl** [ABausG/home_widget#29]
We have a widget that shows the current state, filllevel, ... of an energy storage Unit, and we would like to show either Status: OK in black or Status: ERROR in red?

The data for this widget comes from a rest api, is there any way to programmatically update the textfield to red background as soon as the api returns an error? As far as I could see there is only support for updateWidget and set the text and nothing else?

**Comment by ABausG** [comment]
Check the example of background updates. You should be able to do the call in the background (either with the workmanager plugin or look for other solutions) and once you have the result you can call `HomeWidget.saveData` and `HomeWidget.updateWidget`

**Comment by jkbngl** [comment]
perfect thanks a lot we managed to update the style!
