### ISSUE TITLE
[BUG]"initiallyLaunchedFromHomeWidget" used to work, but it doesn't seem to have an effect in newer versions of Xcode or Flutter. "widgetClicked" works fine though.

### ISSUE THREAD

**Issue by Allenxuxu** [ABausG/home_widget#292]
### Problem to solve

Everything used to work fine, but after I upgraded Xcode or Flutter, "initiallyLaunchedFromHomeWidget" is not working. "widgetClicked" still works as expected.

Here are my current versions:
Xcode version: 15.3.0
Flutter: 3.19.2

### Proposal

-

### Which Platform would be improved?

iOS

### Other

- [ ] Are you interested in working on a PR for this?

**Comment by abhishekbbbbbb** [comment]
hey @Allenxuxu i'm facing one issue with this plugin 


when i add this decorator @available(iOSApplicationExtension 13.0, ) over 

//
//  HomeWidgetBackgroundIntent.swift
//  home_widget
//
//  Created by Anton Borries on 25.08.23.
//

import Flutter
import Foundation
import Swift


@available(iOSApplicationExtension 13.0, *)
public struct HomeWidgetBackgroundWorker {

  static let dispatcherKey: String = "home_widget.internal.background.dispatcher"
  static let callbackKey: String = "home_widget.internal.background.callback"

  static var engine: FlutterEngine?
  static var channel: FlutterMethodChannel?

  static var isSetupCompleted: Bool = false
  static var continuations: [CheckedContinuation<Void, Never>] = []

  private static var registerPlugins: FlutterPluginRegistrantCallback?

  public static func setPluginRegistrantCallback(registerPlugins: FlutterPluginRegistrantCallback) {
    self.registerPlugins = registerPlugins
  }

  /// Call this method to invoke the callback registered in your Flutter App.
  /// The url you provide will be used as arguments in the callback function in dart
  /// The AppGroup is necessary to retrieve the dart callbacks
  static public func run(url: URL?, appGroup: String) async {
    if isSetupCompleted == false {
      await withCheckedContinuation { continuation in
        continuations.append(continuation)
      }
    }

    let preferences = UserDefaults.init(suiteName: appGroup)
    let dispatcher = preferences?.object(forKey: dispatcherKey) as! Int64
    NSLog("Dispatcher: \(dispatcher)")

    await sendEvent(url: url, appGroup: appGroup)
  }

  static func setupEngine(dispatcher: Int64) {
    engine = FlutterEngine(
      name: "home_widget_background", project: nil, allowHeadlessExecution: true)

    channel = FlutterMethodChannel(
      name: "home_widget/background", binaryMessenger: engine!.binaryMessenger,
      codec: FlutterStandardMethodCodec.sharedInstance()
    )
    let flutterCallbackInfo = FlutterCallbackCache.lookupCallbackInformation(dispatcher)
    let callbackName = flutterCallbackInfo?.callbackName
    let callbackLibrary = flutterCallbackInfo?.callbackLibraryPath

    let started = engine?.run(
      withEntrypoint: flutterCallbackInfo?.callbackName,
      libraryURI: flutterCallbackInfo?.callbackLibraryPath)
    if registerPlugins != nil {
      registerPlugins?(engine!)
    } else {
      HomeWidgetPlugin.register(with: engine!.registrar(forPlugin: "home_widget")!)
    }

    channel?.setMethodCallHandler(handle)
  }

  public static func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    switch call.method {
    case "HomeWidget.backgroundInitialized":
      isSetupCompleted = true
      while !continuations.isEmpty {
        let continuation = continuations.removeFirst()
        continuation.resume()
      }
      result(true)
    default:
      result(FlutterMethodNotImplemented)
    }
  }

  static func sendEvent(url: URL?, appGroup: String) async {
    guard let _channel = channel else {
      return
    }
    let preferences = UserDefaults.init(suiteName: appGroup)
    guard let _callback = preferences?.object(forKey: callbackKey) as? Int64 else {
      return
    }
    await withCheckedContinuation { continuation in
      DispatchQueue.main.async {
          _channel.invokeMethod("", arguments: [_callback, url?.absoluteString ?? ""]) { _ in
          continuation.resume()
        }
      }
    }
  }
}



my application stops working for the iphones below 17.0 can u please tell how can i fix this issue

**Comment by ItzBubschki** [comment]
I encountered a similar issue where my app was unable to detect if it was opened from a widget, regardless of using `initiallyStarted` or `widgetClicked`. 

While debugging, I noticed an error message along the lines of "AppGroupId missing". To resolve this, I added the app group ID using `setAppGroupId` before calling `initiallyLaunchedFromWidget`, and this fixed the issue.

It seems likely that in your case, `setAppGroupId` is being called at a different point in the app, allowing it to detect `widgetClicked`.

This should definitely be added to the documentation: the app group ID must be set first to ensure proper detection on iOS.

**Comment by Allenxuxu** [comment]
> I encountered a similar issue where my app was unable to detect if it was opened from a widget, regardless of using `initiallyStarted` or `widgetClicked`.
> 
> While debugging, I noticed an error message along the lines of "AppGroupId missing". To resolve this, I added the app group ID using `setAppGroupId` before calling `initiallyLaunchedFromWidget`, and this fixed the issue.
> 
> It seems likely that in your case, `setAppGroupId` is being called at a different point in the app, allowing it to detect `widgetClicked`.
> 
> This should definitely be added to the documentation: the app group ID must be set first to ensure proper detection on iOS.

Thank you very much🙏
