### ISSUE TITLE
Someone help to implement home widget on Xcode 16

### ISSUE THREAD

**Issue by melihcelik09** [ABausG/home_widget#298]
### What happened?

I followed some tutorials also documentation but i can not configured correctly.
I got a too much error related with ios 18 configuration.
For instance i implement home widget but when i try to add simulator instantly crashed.

### Update

I was trying to run example project.It worked in ios 17.5. But my project still got a same issue. 

### What do you expect?

Someone help to how can i configured correctly?

### Relevant log output
```
Invalid `Podfile` file: `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["C0C20F2F2CA582D4002A1F07"], "explicitFileTypes"=>{}, "explicitFolders"=>[], "path"=>"FoodListWidget", "sourceTree"=>"<group>"}
```

`PlatformException(-7, AppGroupId not set. Call setAppGroupId first, null, null)`

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-x64, locale tr-TR)
    • Flutter version 3.24.3 on channel stable at /usr/local/Caskroom/flutter/3.24.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/melihcelik/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/melihcelik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • iPhone 15 (mobile) • F4CC2A9A-7279-483B-9340-2838F1AF4A83 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • iPhone 16 (mobile) • 985C7987-6B8B-4C57-BD20-674C758B6484 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 15.0 24A335 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 129.0.6668.60

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### On which Platform do you experience this issue?

iOS

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by ABausG** [comment]
Based on the Issues it seems one important thing is definitely that you missed setting the app groups.

Can you also try to clean and reinstall your pods given that it looks like a pod issue based on the output you shared

**Comment by melihcelik09** [comment]
> Based on the Issues it seems one important thing is definitely that you missed setting the app groups.
> 
> Can you also try to clean and reinstall your pods given that it looks like a pod issue based on the output you shared

Actually i already set that but still not enough to add widget on simulator.

**Comment by karlludwigweise** [comment]
I can confirm the Cycle inside Runner error @melihcelik09 reports
* on a clean project
* with the latest flutter and 
* the latest home_widget.

**Comment by melihcelik09** [comment]
> Fixed this by moving "Thin Binary" Build Phase to the bottom.

can u share with me build phases order screen shot maybe other people needs when they check issue

<img width="2033" alt="image" src="https://github.com/user-attachments/assets/46bd424c-0807-4fda-8e28-d9d7f88434fa">
this is my build phases order

**Comment by karlludwigweise** [comment]
@melihcelik09 you have "Thin Binary" as second last item. Make it the last item.

**Comment by melihcelik09** [comment]
@karlludwigweise i set it like that and after run it worked but still got a issue i can not add manually widget.

**Comment by karlludwigweise** [comment]
That's another issue I can't help with.

It says something about `Please specify the widget kind in the scheme's Environment Variables using the key ...`. That's a good starting point for you :)

**Comment by melihcelik09** [comment]
Thanks to all ı figured out too many issues but still got a latest error if i run project from xcode widget automatically created otherwise simulator instantly crashed.

**Comment by jonmountjoy** [comment]
I had a similar problem on Xcode 16.0 with the `Cycle inside Runner; building could produce unreliable results`, and the advice of @karlludwigweise - of moving the " moving "Thin Binary" Build Phase to the bottom" worked.  Thank you @karlludwigweise

**Comment by melihcelik09** [comment]
I really appreciate to everyone. I figured out my issue so i can close the issue.

**Comment by ABausG** [comment]
First of all thanks everybody for coming into this. I actually was about to answer in here yesterday afternoon when I found the time but was happily surprised you all already took care of each others problems 🫶 

@melihcelik09 would you have time opening a PR with a proposal where you would've wanted this content in the docs as well as in which form.

If you need help in adding things like screenshots I can help you in the PR.

I guess it should live in the iOS Setup Page? But as you just went through I think it would be great if you could provide the best place where it would've helped you the most.

**Comment by victormanuelfrancodev** [comment]
please add that to the documentation .. I spend many time with that
