### ISSUE TITLE
Possibility to set custom font

### ISSUE THREAD

**Issue by jkbngl** [ABausG/home_widget#30]
We have tried to use a custom Font called Rubik:
https://fonts.google.com/specimen/Rubik

Neither by passing the font to the widget itself, nor with attaching a shared resource from flutter to the native android part. Is this a known limit (of the package/ general) for android as the home widget always inherits the system font?

**Comment by ABausG** [comment]
Never tried custom fonts in Widgets. I think you would need to do it more or less completely native (sharing resources might work) as the HomeScreen Widget is handled by the system itself.
I only had to use custom fonts on Android in an App and it was relatively straightforward to add it via fontfamily int the theme like described here: https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml?hl=de

As the widget is a XML Layout as well this might work. Let me know when you tried this and how it goes

**Comment by ABausG** [comment]
Any luck with this @jkbngl

**Comment by jkbngl** [comment]
hi @ABausG , sorry for not following up on this...

We tried around a bit more, but we strongly suspect that the underlying OS doesnt allow a custom font on the homescreen at all... which is probably fine anyway as it fits better in the whole enviroment, at least this is our conclusion☺

thanks for your interest and I think we can close this ticket.

**Comment by Aderiani** [comment]
I have tried custom font by adding them as a font family in the XML file and it works for most of the Android versions, but some it did not work. To solve that, instead of passing a Textview I passed the text to a Paint canvas with a typeface of the custom font and that works for every android version.
