### ISSUE TITLE
 Nothing happening when I press a widget button

### ISSUE THREAD

**Issue by nizarom** [ABausG/home_widget#306]
### What happened?

Hi, when I press a widget button nothing is happening. Although the rest of the tasks (Widget Update) work fine.
any help please?

Kotlin:
`
val favorisPendingIntent = HomeWidgetBackgroundIntent.getBroadcast(context, Uri.parse("myapp://favoris"))
setOnClickPendingIntent(R.id.favoris, favorisPendingIntent)
`

Dart:
```
@pragma('vm:entry-point')
Future<void> backgroundCallback(Uri? uri) async {
  if (Platform.isAndroid) {
    if (uri?.host == 'favoris') {
      Get.offAllNamed("/", parameters: {'target': 'favoris'});
    }
```

### What do you expect?

i aspect that the button named favoris gona call Get.offAllNamed, the app open and go to favoris page. but nothing is happening.

### Relevant log output

```shell
Nothing
```

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### On which Platform do you experience this issue?

Android

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by ABausG** [comment]
Are you trying to do interactivity (something happens when clicking on the widget) or are you trying clicking on the widget to open the app (you can then still do some actions)

If you try to open/navigate the app you should check this part of the documentation: https://docs.page/abausg/home_widget/features/detect-clicks

**Comment by nizarom** [comment]
i want if i click the  widget button to call a function in the dart/flutter: click -> if (uri?.host == 'favoris') -> open the app -> go to favoris page.

**Comment by ABausG** [comment]
You want to check out the `detect-click` documentation then. This should provide everything you want to do with this.
