### ISSUE TITLE
I want support about widget for iOS

### ISSUE THREAD

**Issue by vidicphan** [ABausG/home_widget#32]
I see code:        name: 'HomeWidgetExampleProvider', iOSName: 'HomeWidgetExample');

I don't see about clase HomeWidgetExampleProvider
Where are this? 
Thank you for support

**Comment by ABausG** [comment]
Android:

https://github.com/ABausG/home_widget/blob/main/example/android/app/src/main/kotlin/es/antonborri/home_widget_example/HomeWidgetExampleProvider.kt


iOS:

https://github.com/ABausG/home_widget/blob/main/example/ios/HomeWidgetExample/HomeWidgetExample.swift
