### ISSUE TITLE
Update ImageView

### ISSUE THREAD

**Issue by roly151** [ABausG/home_widget#34]
Is it possible to update an ImageView in the widget from Flutter assets? I have a weather app and looking to update the weather forecast icon on the widget, but I'm struggling to figure out how to do it. I can update a resource file, but I'd prefer not to have to have two copies. I'm only a beginner, so using this to learn. Any help would be appreciated. Thanks.

**Comment by ABausG** [comment]
You could encode the image in flutter to base64 and send that as data to the widget where you then decode it from base64 back to a image

**Comment by roly151** [comment]
Perfect - thank you, that worked.
