### ISSUE TITLE
MissingPluginException(No implementation found for method registerBackgroundCallback on channel home_widget)

### ISSUE THREAD

**Issue by roly151** [ABausG/home_widget#39]
Fairly new to all of this. I had Android working perfectly and tried to add an ios widget. I'm using workmanager to try to update the widget in the back ground. However I am getting this error. 

The error also occurs on the example app. 

For me this error occurs when I try to get data from an api using the http package. 

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method registerBackgroundCallback on channel home_widget)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Error 8, kCLErrorDomain, The operation couldn’t be completed. (kCLErrorDomain error 8.), null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      LocalGeocoding.findAddressesFromQuery (package:geocoder/services/local.dart:18:28)
<asynchronous suspension>
#3      _WeatherAppState.getLatLngFromLocation (package:weatherapp/main.dart:614:21)
<asynchronous suspension>

As I'm new to this - please let me know what you need.

**Comment by peter100u** [comment]
do you have solve ? i have a error with you some

**Comment by ABausG** [comment]
Could you share a Repository a bit more code to see where this might be coming from?

**Comment by ABausG** [comment]
If I understand you correctly this error occurs on iOS and in combination with workmanager?

Did you remember to add the following to your AppDelegate?
It is required to register other Plugins (home_widget in this case) to the Workmanager so that in calls of Workmanager these plugins can be accessed 

```swift
WorkmanagerPlugin.setPluginRegistrantCallback { registry in
    GeneratedPluginRegistrant.register(with: registry)
}
```

**Comment by Manuito83** [comment]
Hi, not sure if this is related, but I think so.

I'm using the official example app that is hosted in GitHub (v0.1.4), with no modifications at all. 

On launch (iOS) I get this:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method registerBackgroundCallback on channel home_widget)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
```

I can't update the widget (or use any of the other two buttons' functionality).

Android is working fine.

**Comment by roly151** [comment]
Hi, apologies for the delay. Yes, this occurs on iOS, and in combination with work manager. I have added the code you posted to AppDelegate, but it doesn't help. 

I think I have narrowed it down to the http plugin. Stepping through the code, the error occurs when I try to use the http plugin to query an api. I've explained it a little more here: https://stackoverflow.com/questions/69200965/flutter-home-widgets-on-ios-missingpluginexceptionno-implementation-found-for 

Not sure if this helps at all?

**Comment by ABausG** [comment]
There is indeed no implementation for the `registerBackgroundCallback` function on iOS thus far as there is no support for interactive HomeScreenWidgets on iOS. However this should be fixed with #53

**Comment by Manuito83** [comment]
Thank you, you were completely right. I had a look at the README several times, but for some reason I didn't notice that the relevant setup sections for Android and iOS were expandable.

**Comment by ABausG** [comment]
The fixed is released in https://github.com/ABausG/home_widget/releases/tag/v0.1.5
