### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'bool' is not a subtype of type 'String?' in type cast 

### ISSUE THREAD

**Issue by chame10** [ABausG/home_widget#40]
i have an error when i click the arrow back on android and then i open the app with the home screen widget.

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'bool' is not a subtype of type 'String?' in type cast
E/flutter (14900): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:41)
E/flutter (14900): <asynchronous suspension>.

this is the erro, i try to check this, but i can't resolved, it just happen when you go back and then u click the widget to open the app again cause android destroy the app, and then idk why cannot rebuild well.
 Destroying service.
D/FlutterLocationService(14900): Creating service.
D/FlutterLocationService(14900): Binding to location service.

**Comment by chame10** [comment]
void _checkForWidgetLaunch() {
    HomeWidget.initiallyLaunchedFromHomeWidget().then(_launchedFromWidget);
  }
 today i anylize my code and descover when u destroy de app this method is returning the error. i know cause i print .catchError and print this type 'bool' is not a subtype of type 'String?' in type cast that is the same i think is not referencing the uri or what???

**Comment by roly151** [comment]
I have the same error.

**Comment by ABausG** [comment]
What platform is this appearing on? Android or iOS?

**Comment by roly151** [comment]
It's on Android for me.

**Comment by chame10** [comment]
i fixed this one with url in the container, as u know the title and subtitle has one but the container no.
