### ISSUE TITLE
Multiple Widgets

### ISSUE THREAD

**Issue by roly151** [ABausG/home_widget#41]
Is it possible to have multiple widgets that update in the background? I have managed to get two widgets, but cannot get one of them to update in the background. 

I have two HomeWidgetProvider Classes, two widget info xml's, two layout xml's, and have two receivers in the manifest. I only have one of the following - I'm assuming this is okay?
`
<receiver android:name="es.antonborri.home_widget.HomeWidgetBackgroundReceiver">
            <intent-filter>
                <action android:name="com.resortstylebeanbags.localweatherau.action.BACKGROUND" />
            </intent-filter>
        </receiver>
        <service android:name="es.antonborri.home_widget.HomeWidgetBackgroundService"
                 android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true"/>
`

**Comment by f-tepel** [comment]
I am wondering the same!
In the example script I saw you get the widget id and can therefore setup an if condition like this.
```
if (test is String && widgetId == 27) {
    val imageBytes = Base64.decode(test, Base64.DEFAULT)
    val decodedImage = BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.size, BitmapFactory.Options().apply {
        inSampleSize = 10
    })
    setImageViewBitmap(R.id.widget_image, decodedImage)
}
```

So if I can somehow store which widgets exist and which ids they have, I could update the widgets by sending the widget id to kotlin. The problem is that I don't know how to get the widget id into the flutter app. Is there any event firing when a widget is created?

**Comment by f-tepel** [comment]
I hacked something together which is not really nice for the user experience but it works.
We could use the broadcast mechanism to get the widget id. At first the user adds a widget, then he has to click it and we can register it.

Send the widget id like this to flutter:
```
val backgroundIntent = HomeWidgetBackgroundIntent.getBroadcast(
        context,
        Uri.parse("homeWidgetExample://titleClicked?widgetid=" + widgetId.toString())
)
setOnClickPendingIntent(R.id.widget_image, backgroundIntent)
```

Then read and handle it here in your main.dart
```
void backgroundCallback(Uri data) async {
  print(data);
  print(data.query);

  if (data.host == 'titleclicked') {
    await HomeWidget.saveWidgetData<String>('test', await getImageBase());
    await HomeWidget.updateWidget(
        name: 'HomeWidgetExampleProvider', iOSName: 'HomeWidgetExample');
  }
}
```

**Comment by roly151** [comment]
Luckily I don't need the widget id. I've managed to get my second widget updating in the background, but the sync button I have is not working. (I have a button on the widget that updates the data when clicked). The button on the first widget calls the backgroundCallback function, but the button on the second widget doesn't. Not sure why. I'm assuming the background receiver in my manifest (pasted above) would receive both - but perhaps not.  This is my second widget intent in the second widget appprovider.

val lw01_refreshIntent = HomeWidgetBackgroundIntent.getBroadcast(
                    context,
                    Uri.parse("lw01_widget://syncclicked")
                )
setOnClickPendingIntent(R.id.lw01_syncButton, lw01_refreshIntent)

**Comment by adrianvintu** [comment]
I have just build 2 widgets, by duplicating /xml/, layout, provider classes and registration AnroidManifest.xml.

What I have forgotten, and my new widget would not update, was to duplicate code

```
    await HomeWidget.updateWidget(name: 'Widget1', iOSName: 'Widget1');
    await HomeWidget.updateWidget(name: 'Widget2', iOSName: 'Widget2');
```

Hope it helps someone.

**Comment by qasim90** [comment]
I was able to implement multiple widgets on Android but not sure how to do this on iPhone. I've created two iOS widgets but in widgets gallery I only see one widget with 3 different sizes. The second widget is not available anywhere. Can somebody help?

**Comment by sreerag2460** [comment]
> Is it possible to have multiple widgets that update in the background? I have managed to get two widgets, but cannot get one of them to update in the background.
> 
> I have two HomeWidgetProvider Classes, two widget info xml's, two layout xml's, and have two receivers in the manifest. I only have one of the following - I'm assuming this is okay? `<receiver android:name="es.antonborri.home_widget.HomeWidgetBackgroundReceiver"> <intent-filter> <action android:name="com.resortstylebeanbags.localweatherau.action.BACKGROUND" /> </intent-filter> </receiver> <service android:name="es.antonborri.home_widget.HomeWidgetBackgroundService" android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true"/>`



only receiver and provider need to make multiple, then what about the widget (GlanceAppWidget)file?
