### ISSUE TITLE
Delay Problem on Background Intent

### ISSUE THREAD

**Issue by GoldenSoju** [ABausG/home_widget#43]
Hi, first of all thanks for your package!

When working with home screen widgets on Android, I realized that the background intent (_HomeWidgetBackgroundIntent.getBroadcast_) sometimes suddenly gets into a delayed state. I thought I implemented something wrong, but after checking, it seems to also happen with the sample from the package (change title on click).

https://user-images.githubusercontent.com/42365471/134796763-f2c8c254-8607-4c8a-b58c-d0458fb5b22c.mp4

I tested on emulator (API 29) and also on my phone (API 30), it shows the same behaviour.

If it enters the delayed state, the next update happens >10 seconds after a click, sometimes earlier, or sometimes when you click on the widget to open the app (_HomeWidgetLaunchIntent.getActivity_).

I tried to find  something in the logs but without any success.
So I was wondering if you maybe know, what is causing the delays (and maybe how to avoid them) ?

**Comment by ABausG** [comment]
I believe this delay is a limitation by the system as the Widget is owned by the HomeScreen and not the App itself (hence having to write it natively)

https://developer.android.com/guide/topics/appwidgets/advanced#update-widgets

Maybe the duration could be tweaked but ultimately the time is dictated by the system.

However I would argue that for most use cases of a Home Screen Widget a delay in the realm of ~10-20 seconds should still be fine.

**Comment by GoldenSoju** [comment]
Thanks for your reply. I indeed went with a complete native solution. 👍
Issue can be closed.
