### ISSUE TITLE
how to update widget data every hour?

### ISSUE THREAD

**Issue by jinfagang** [ABausG/home_widget#44]
Hi, I want update widget showing data from a http get request every hour.

Where should I place this code? in flutter or somewhere?

**Comment by aljkor** [comment]
I think you should look into workmanager flutter package. Register periodic task where you call your API every hour and save the data into home widget using `HomeWidget.saveWidgetData` and then `HomeWidget.updateWidget` to update it. This should be done in flutter.

**Comment by jinfagang** [comment]
@aljkor  thank u, then the only question is, if I saved new data with `HomeWidget.saveWidgetData` every hour, will Homwidget restart Widget automatically? By how?

**Comment by aljkor** [comment]
`HomeWidget.updateWidget` should force a reload of home widget when called.

**Comment by ABausG** [comment]
Thanks for answering @aljkor I will close this for now. If you have any more questions @jinfagang feel free to reopen this
