### ISSUE TITLE
UIApplication:open handler is conflicting with uni_links plugin

### ISSUE THREAD

**Issue by ajinasokan** [ABausG/home_widget#47]
As per Flutter engine implementation `UIApplication:open` is suppose to return `false` if link is not handled by the plugin.

https://github.com/flutter/engine/blob/138c91c614d742c52aa5432b4cb921f0ff9fdee2/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm#L313-L327

But in home_widget plugin it is always returning `true` and this blocks plugins like `uni_links` to get the URL. 

https://github.com/ABausG/home_widget/blob/6559612e09ad70dd8483670ab8289dcc73226ca9/ios/Classes/SwiftHomeWidgetPlugin.swift#L134-L139

I have a fix in #46 that properly returns the flag.

**Comment by ABausG** [comment]
Fixed by #42 will be in the next release
