### ISSUE TITLE
clickPendingIntentTemplate

### ISSUE THREAD

**Issue by proczak1** [ABausG/home_widget#52]
Hey, 
is there a way to setup pendingIntentTemplate with background click. If I use 
"HomeWidgetBackgroundIntent.getBroadcast(context)" 
for setPendingIntentTemplate, then data sent with setOnClickFillInIntent is empty

**Comment by ABausG** [comment]
Could you please provide a bit more context on what you are trying to achieve?

**Comment by proczak1** [comment]
Yeah sorry, that was a bit chaotic.

When on android app widget we got a list of items, we need to specify ooclicks that way:
`// template to handle the click listener for each item
        val clickIntentTemplate = Intent(context, MainActivity::class.java)
        val clickPendingIntentTemplate: PendingIntent = TaskStackBuilder.create(context)
            .addNextIntentWithParentStack(clickIntentTemplate)
            .getPendingIntent(0, PendingIntent.FLAG_UPDATE_CURRENT)

        views.setPendingIntentTemplate(R.id.widgetListView, clickPendingIntentTemplate)` 

So if I put it like that (it opens the app) - it works fine ( with fill in intent in items:

`  Intent fillInIntent = new Intent(mContext, MainActivity.class);
        fillInIntent.setData(Uri.parse("AgendaWidget://itemClick?" +
                "type=" + agendaItem.type +
                "&id=" + agendaItem.key +
                "&parentId=" + agendaItem.parentId +
                "&timestamp=" + agendaItem.timestamp
        ));
        fillInIntent.setAction(HomeWidgetLaunchIntent.HOME_WIDGET_LAUNCH_ACTION);
        fillInIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        rv.setOnClickFillInIntent(R.id.widgetItemContainer, fillInIntent);`

Now what i want to achive is backgroundClick in list item (not opening app, just backgroundCallback). 
How would i do that?

**Comment by ABausG** [comment]
(Taken from [HomeWidgetExampleProvider](https://github.com/abausg/home_widget/tree/main/example/android/app/src/main/kotlin/es/antonborri/home_widget_example/HomeWidgetExampleProvider.kt))
```kotlin
val backgroundIntent = HomeWidgetBackgroundIntent.getBroadcast(
        context,
        Uri.parse("homeWidgetExample://titleClicked")
)
setOnClickPendingIntent(R.id.widget_title, backgroundIntent)
```

If you adjust the Uri you pass in based on the item clicked you should get that uri as a parameter in the backgroundCallback you register with `HomeWidget.registerBackgroundCallback`
Does that help you?
Also just to be sure: You have added the Background Service to your manifest [as described here](https://github.com/ABausG/home_widget#androidnative-part)?

**Comment by proczak1** [comment]
Backgroundcallback works fine for me, if I set setOnClickPendingIntent. The problem is, when using setPendingIntentTemplate as documentation says: 
`When using collections (eg. ListView, StackView etc.) in widgets, it is very costly to set PendingIntents on the individual items, and is hence not recommended. Instead this method should be used to set a single PendingIntent template on the collection, and individual items can differentiate their on-click behavior using setOnClickFillInIntent(int, Intent).`

**Comment by ABausG** [comment]
Could you give me a link to the documentation? I need to take a deeper look into that

**Comment by proczak1** [comment]
Tried using those two:
https://developer.android.com/reference/android/widget/RemoteViews#setOnClickPendingIntent(int,%20android.app.PendingIntent)

https://developer.android.com/reference/android/widget/RemoteViews#setOnClickFillInIntent(int,%20android.content.Intent)

**Comment by proczak1** [comment]
Tried to put it that way:

 val clickIntentTemplate = Intent(context, HomeWidgetBackgroundReceiver::class.java)
        val clickPendingIntentTemplate: PendingIntent = TaskStackBuilder.create(context)
            .addNextIntentWithParentStack(clickIntentTemplate)
            .getPendingIntent(0, PendingIntent.FLAG_IMMUTABLE)
        views.setPendingIntentTemplate(R.id.special_shopping_list, clickPendingIntentTemplate)

But it throws: 

Caused by: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.MYPACKAGE/es.antonborri.home_widget.HomeWidgetBackgroundReceiver}

**Comment by JangamRuthvik** [comment]
@ABausG @proczak1 i also want to acheive the same thing. i have list of my task each having unique uuid and on clicking it, i will receive corresponding uuid from streamlistener and then open the task details page . but the main problem is how can i assign uuid to that ListTile. if you want further details i am ready to share my code

**Comment by can-cc** [comment]
> Tried to put it that way:
> 
> val clickIntentTemplate = Intent(context, HomeWidgetBackgroundReceiver::class.java) val clickPendingIntentTemplate: PendingIntent = TaskStackBuilder.create(context) .addNextIntentWithParentStack(clickIntentTemplate) .getPendingIntent(0, PendingIntent.FLAG_IMMUTABLE) views.setPendingIntentTemplate(R.id.special_shopping_list, clickPendingIntentTemplate)
> 
> But it throws:
> 
> Caused by: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.MYPACKAGE/es.antonborri.home_widget.HomeWidgetBackgroundReceiver}



> Tried to put it that way:
> 
> val clickIntentTemplate = Intent(context, HomeWidgetBackgroundReceiver::class.java) val clickPendingIntentTemplate: PendingIntent = TaskStackBuilder.create(context) .addNextIntentWithParentStack(clickIntentTemplate) .getPendingIntent(0, PendingIntent.FLAG_IMMUTABLE) views.setPendingIntentTemplate(R.id.special_shopping_list, clickPendingIntentTemplate)
> 
> But it throws:
> 
> Caused by: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.MYPACKAGE/es.antonborri.home_widget.HomeWidgetBackgroundReceiver}



> Tried to put it that way:
> 
> val clickIntentTemplate = Intent(context, HomeWidgetBackgroundReceiver::class.java) val clickPendingIntentTemplate: PendingIntent = TaskStackBuilder.create(context) .addNextIntentWithParentStack(clickIntentTemplate) .getPendingIntent(0, PendingIntent.FLAG_IMMUTABLE) views.setPendingIntentTemplate(R.id.special_shopping_list, clickPendingIntentTemplate)
> 
> But it throws:
> 
> Caused by: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.MYPACKAGE/es.antonborri.home_widget.HomeWidgetBackgroundReceiver}

Hi, Did you found the solution?

**Comment by Ayush783** [comment]
I worked on a similar challenge, setOnClickFillInIntent was not adding data to the PendingIntent because of PendingIntent.FLAG_IMMUTABLE, I had to change it to PendingIntent.FLAG_MUTABLE to make it work or PendingIntent.FLAG_UPDATE_CURRENT for lower android versions.

**Comment by ABausG** [comment]
Reading back through this I think this should be possible to achieve this by creating a custom Intent and just setting the desired action itself. Will close this for now
