### ISSUE TITLE
How can I create listView?

### ISSUE THREAD

**Issue by hatano0x06** [ABausG/home_widget#56]
Hello!

This is great package for me that not good at Android and iOS.

I want to create home screen widget like gmail ( topbar + listview widget ) in Android 
![screen-3](https://user-images.githubusercontent.com/7422251/144100336-a0d24aba-0009-4bad-af49-f7a68d942d10.jpg)
)

Can I create a listview widget with this package?
And if it is possible, how do we do it?

**Comment by ABausG** [comment]
Hey, you need to create the widget using the native tools provided by Android (with this plugin the views need to be created using the native tools).

As a starting point for Lists check this out: https://developer.android.com/guide/topics/appwidgets/collections
This should give you a good starting point to create the ListView in a widget
