### ISSUE TITLE
Button in iOS Widget

### ISSUE THREAD

**Issue by lucasribolli** [ABausG/home_widget#57]
I see that the `registerBackgroundCallback` feature released in 0.1.2 version is not available in iOS. Is there a limitation in iOS platform? 
I have seen that widgets click in iOS can just open app using DeepLink (like already implemented in that plugin) but I am not sure about it.

I appreciate any answer.

**Comment by ABausG** [comment]
Yes, currently iOS does not support interactive elements on widgets. That's why the plugin does not support it. As soon as Apple adds support I will work on adding it to the plugin
