### ISSUE TITLE
Target of URI doesn't exist: package

### ISSUE THREAD

**Issue by tim-teacher** [ABausG/home_widget#60]
`import 'package:home_widget/home_widget_callback_dispatcher.dart';`
Show error:
`Target of URI doesn't exist: 'package:home_widget/home_widget_callback_dispatcher.dart'.`

`Undefined name 'HomeWidget'.`

But plugin was added, `flutter get `was called many times.

`home_widget: ^0.1.5`

**Comment by ABausG** [comment]
Please try importing:

`import 'package:home_widget/home_widget.dart';`
