### ISSUE TITLE
flutter_workmanager crashes app on S

### ISSUE THREAD

**Issue by adrianvintu** [ABausG/home_widget#63]
Please consider updating the documentation to remove `flutter_workmanager` as it looks unmaintained and it straight up crashes on the emulator S as per https://github.com/fluttercommunity/flutter_workmanager/issues/352.

An easy replacement could be https://pub.dev/packages/android_alarm_manager_plus.

**Comment by Aderiani** [comment]
I used the Android alarm manager for Anroid and it worked perfectly. But the problem is to find a substitute for IOS.

**Comment by ABausG** [comment]
This is now fixed in the latest version. Also note that this only affects the example app and not the widget itself
