### ISSUE TITLE
Background refreshing of IOS when the widget is tapped. 

### ISSUE THREAD

**Issue by Aderiani** [ABausG/home_widget#64]
In IOS 13 and later, to be able to use background refreshing of the app, the BGTaskScheduler should be used and the UIApplication does not work. 
https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app

**Comment by ABausG** [comment]
So as far as I know tapping a widget on iOS will always open the App.
If you want to do (periodic) background work on iOS this is not part of this plugin.
There is a small section in the readme about this: https://github.com/ABausG/home_widget#background-update

The work manager plugin only supports one-off tasks however these should work already with the plugin (please note the hint in the readme about plugin registration). So a way could be to schedule multiple one-off tasks to update the data periodically

Unfortunately I had not yet have the time to try out more background work plugins that could help with this.
