### ISSUE TITLE
ListView Help

### ISSUE THREAD

**Issue by Nightbl927** [ABausG/home_widget#65]
I have been trying to figure out how to add a ListView with programmatically updatable TextViews within the ListView but I am unsure of how to accomplish this.  Does anyone have any suggestions?

Thank you

**Comment by deyanemo** [comment]
this tutorial helped me a lot 
https://www.youtube.com/watch?v=xGQJg31TPtU&list=PLrnPJCHvNZuDCoET8jL2VK4YVRNhVEy0K

**Comment by ABausG** [comment]
@Nightbl927 can this be closed? Also is this in any way related to #52 ?

**Comment by Nightbl927** [comment]
@ABausG yes, I can close it now.  It seems like to get dynamic data in the ListView, I will have to work more on the native end.
