### ISSUE TITLE
Update widget every second

### ISSUE THREAD

**Issue by erperejildo** [ABausG/home_widget#68]
I tried this but doesn't work:
`Workmanager.registerPeriodicTask('1', 'widgetBackgroundUpdate', frequency: Duration(seconds: 1));`
get this error:
`Interval duration lesser than minimum allowed value; Changed to 900000`. That's the 15 default minutes. Is not possible to reduce this limit anyhow?

My app shows how much money you earn/pay by second so I need a widget to show also same info without opening the app (more info: https://play.google.com/store/apps/details?id=com.drodriguez.profits)

**Comment by aljkor** [comment]
I believe this is not possible with workmanager. If you schedule your background update too frequently it consumes a lot of resources and impacts battery life. This is why Android OS blocks tasks that want to be executed in less then 15 minutes. It just ensures that the task is ran once per interval (could be at the start of the 15 min interval, at the end or somewhere in the middle).

**Comment by erperejildo** [comment]
> I believe this is not possible with workmanager. If you schedule your background update too frequently it consumes a lot of resources and impacts battery life. This is why Android OS blocks tasks that want to be executed in less then 15 minutes. It just ensures that the task is ran once per interval (could be at the start of the 15 min interval, at the end or somewhere in the middle).

fair enough. Thanks for the update
