### ISSUE TITLE
more example please

### ISSUE THREAD

**Issue by nesteiner** [ABausG/home_widget#69]
I have to say, the code in `example` can't compile at all, I found that
```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"
```
and I have goggled but found there are only one useful tutorial about using `home_widget`  https://medium.com/@ashishgarg1998/how-to-create-home-screen-app-widgets-in-flutter-ce3458f3638e  
can you give more example for using `home_widget`?

**Comment by dario-digregorio** [comment]
Here is another one :)
https://codelabs.developers.google.com/flutter-home-screen-widgets#0

**Comment by ABausG** [comment]
@Fethi-Hamdani Yes!

**Comment by Fethi-Hamdani** [comment]
@ABausG  where can I find docs or examples about that?
I'm getting this error 
`error: HomeWidgetBackgroundIntent() has private access in HomeWidgetBackgroundIntent
            HomeWidgetBackgroundIntent homeWidgetBackgroundIntent = new HomeWidgetBackgroundIntent();`

**Comment by Fethi-Hamdani** [comment]
@ABausG here is it #157
