### ISSUE TITLE
Unresolved reference: R

### ISSUE THREAD

**Issue by tomriddle7** [ABausG/home_widget#7]
I copied files in kotlin/es/antonborri/home_widget_example and launched main.dart but it says Unresolved reference: R

I think that this line makes error.

> val views = RemoteViews(context.packageName, R.layout.example_layout).apply {

Do I have to import R to my project?

**Comment by ABausG** [comment]
Did you create the Layout File?
I would advise to do the actual Android Programming in Android Studio as that will provide you with the best code suggestions

**Comment by tomriddle7** [comment]
Sure. I created same layout file as in example. And I created Widget Configuration and WidgetReceiver.

**Comment by ABausG** [comment]
Does the issue persist after building it?

**Comment by tomriddle7** [comment]
https://github.com/tomriddle7/Dotgasaki
this is my project.

**Comment by leonardocustodio** [comment]
@tomriddle7 the problem about your project is that you created a kotlin/es/antonborri/home_widget_example directory.
This part of the example "HomeWidgetExampleProvider.kt" should be in your home directory so for your project, it should be in: kotlin/com/tomriddle7/dotgasaki/

Regards,

**Comment by tomriddle7** [comment]
@leonardocustodio It was very useful tip. It works well. Thanks.

**Comment by jinfagang** [comment]
@leonardocustodio I got same error, but I am not create such wrong package name directories, Still says can not resolve R.

![image](https://user-images.githubusercontent.com/21303438/137152513-424f14f3-4a03-4d74-b35d-5521f830083b.png)


any idea?

**Comment by petrnymsa** [comment]
@jinfagang  Did you managed to solve this?

**Comment by ABausG** [comment]
I think this is an issue with how the android framework is loaded. It should also appear in files like the `MainActivity.kt` that are created by Flutter itself.

Do you have AndroidStudio installed? Could you try (in vscode/intellij/android studio) right click on the `android/` folder and say `flutter -> Open Android Module in Android Studio`

**Comment by ABausG** [comment]
@jinfagang @petrnymsa do you receive actual runtime errors or is this more or less only when viewing the files in the IDE?

**Comment by petrnymsa** [comment]
@ABausG  Acutally runtime errors, but I've managed to in the end compile it BUT (and I know this should belong to separate issue probably). 

I think whole "example" is wrong?  Because there is no simply `setOnClickPendingIntent` as standalone method, instead I've found this solution: 

```
 val views = RemoteViews(context.packageName, R.layout.widget_layout)
        val pendingIntent = HomeWidgetLaunchIntent.getActivity(context, MainActivity::class.java)
        views.setOnClickPendingIntent(R.id.widget_base_layout, pendingIntent)
        ```
        
        Which unfortunately does not work too...

**Comment by moslite** [comment]
> ![image](https://user-images.githubusercontent.com/21303438/137164461-615f6130-edcd-4767-8efb-9d2f5c44af37.png)
> 
> How do I make these red error gone? I already added the lib dependencies in pubspec.yml

same error here, any idea?
