### ISSUE TITLE
registerBackgroundCallback is only for Android?

### ISSUE THREAD

**Issue by desmeit** [ABausG/home_widget#76]
I don't understand the purpose of registerBackgroundCallback. Is this only for Android? When exactly is this triggered?
What exactly is meant by the explanation in the docs?: `This will get called when a user clicks on the View`

**Comment by ABausG** [comment]
Yes this is only supported on Android right now as this enables interactive Widgets which are not supported on iOS as of writing this comment.

It's purpose is to be notified about clicks on a widget that trigger code in the app but do not open it. An example could be a Widget for a smart Home App that has a switch to turn a light on/off from a widget
