### ISSUE TITLE
ld: framework not found Flutter

### ISSUE THREAD

**Issue by casualcoder404** [ABausG/home_widget#77]
My app and the home widgets used to work properly but due to some reason it is now showing ld: framework not found Flutter
clang: error: linker command failed with exit code 1 (use -v to see invocation) (in XCode) and Flutter framework not found when i flutter run.

**Comment by casualcoder404** [comment]
Has anyone else encountered this or know any solution?
I am really scratching my head over this.

**Comment by ABausG** [comment]
Could you post some more code from your widget implementation and explain what you are trying to do?

 I don't think there should be any references to flutter in the extension

**Comment by devanshkaria88** [comment]
Hello,

@ABausG  @casualcoder404 Did you get any solution or root cause for this issue? Am facing the same issue for one of my Production apps and I couldn't get started on it.. however it works perfectly fine on apps made from scratch.

Regards,
Devansh.

**Comment by ABausG** [comment]
@casualcoder404 @devanshkaria88 Is this still an issue?

**Comment by renanhiramatsu** [comment]
I am facing the same issue.
ld: framework not found uv
clang: error: linker command failed with exit code 1 (use -v to see invocation)


During the linking process. New projects works just fine

**Comment by ABausG** [comment]
I think this is some Xcode issue. I sometimes run into this for the example apps. As a last resort you should recreate the iOS parts and add your files again afterwards. There seems to be a hiccup somewhere in the Xcode build chain
