### ISSUE TITLE
Can reload home widget for platform Android, while platform iOs is not

### ISSUE THREAD

**Issue by huytower** [ABausG/home_widget#8]
Hello bro,

I can reload home widget for platform Android,
while platform iOs is not.

I can replace content "..." by other content in platform Android, while can not in platform iOs.
![Screen Shot 2020-11-19 at 16 48 22](https://user-images.githubusercontent.com/11640136/99649660-11a66080-2a87-11eb-9498-ee095c10d8f4.png)

Please tell me what I need to do more.

**_Code sample :_**

_I used this in main widget as guide told me._
```
@override
  void initState() {
    super.initState();
    // HOME_SCREEN_WIDGET_ID : nct_home_widget
    HomeWidget.setAppGroupId(Constants.HOME_SCREEN_WIDGET_ID); 
  }
```

_I'm using these code for update data (it works for platform Android)_
![Screen Shot 2020-11-19 at 16 12 48](https://user-images.githubusercontent.com/11640136/99647767-ce4af280-2a84-11eb-81c7-1ef6d9989284.png)
![Screen Shot 2020-11-19 at 16 12 41](https://user-images.githubusercontent.com/11640136/99647774-d014b600-2a84-11eb-8d95-16e20c1b479b.png)

_iOs files structure: (HomeWidgetExample created as Widget Extension in Xcode)_
![Screen Shot 2020-11-19 at 16 47 15](https://user-images.githubusercontent.com/11640136/99649556-ec195700-2a86-11eb-8bf2-5c7cb77254c2.png)

_*.entitlements_
![Screen Shot 2020-11-19 at 16 14 15](https://user-images.githubusercontent.com/11640136/99647986-166a1500-2a85-11eb-8deb-be073339fe5a.png)

_HomeWidgetExample.swift_
```
//
//  widget.swift
//  widget

import WidgetKit
import SwiftUI
import Intents

private let widgetGroupId = "nct_home_widget"

struct Provider: TimelineProvider {
    func placeholder(in context: Context) -> ExampleEntry {
        ExampleEntry(date: Date(), title: "Placeholder Title", message: "Placeholder Message")
    }

    func getSnapshot(in context: Context, completion: @escaping (ExampleEntry) -> ()) {
        let data = UserDefaults.init(suiteName:widgetGroupId)
        let entry = ExampleEntry(date: Date(), title: data?.string(forKey: "title") ?? "No Title Set", message: data?.string(forKey: "message") ?? "No Message Set")
        completion(entry)
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> ()) {
        getSnapshot(in: context) { (entry) in
            let timeline = Timeline(entries: [entry], policy: .atEnd)
            completion(timeline)
        }
    }
}

struct ExampleEntry: TimelineEntry {
    let date: Date
    let title: String
    let message: String
}

struct HomeWidgetExampleEntryView : View {
    var entry: Provider.Entry
    let data = UserDefaults.init(suiteName:widgetGroupId)

    var body: some View {
        VStack.init(alignment: .leading, spacing: /*@START_MENU_TOKEN@*/nil/*@END_MENU_TOKEN@*/, content: {
            Text(entry.title).bold().font(/*@START_MENU_TOKEN@*/.title/*@END_MENU_TOKEN@*/)
            Text(entry.message).font(.body)
        }
        )}
}

@main
struct HomeWidgetExample: Widget {
    let kind: String = "nct_home_widget"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: Provider()) { entry in
            HomeWidgetExampleEntryView(entry: entry)
        }
        .configurationDisplayName("nct_home_widget")
        .description("nct_home_widget")
    }
}

struct HomeWidgetExample_Previews: PreviewProvider {
    static var previews: some View {
        HomeWidgetExampleEntryView(entry: ExampleEntry(date: Date(), title: "nct_home_widget", message: "nct_home_widget"))
            .previewContext(WidgetPreviewContext(family: .systemSmall))
    }
}
```

**Comment by ABausG** [comment]
You need to call:
`HomeWidget.updateWidget`
with
```(dart)
iOSName: 'nct_home_widget'
```

**Comment by huytower** [comment]
I already changed as you details,
but it does not work.

What I have missed?

```
Future<void> updateWidget() async {
    print('updateWidget() ');

    try {
      return HomeWidget.updateWidget(
          name: 'HomeWidgetExampleProvider',
          androidName: 'HomeWidgetExampleProvider',
          iOSName: 'nct_home_widget'
      );
          // iOSName: 'HomeWidgetExample');
    } on PlatformException catch (exception) {
      debugPrint('Error Updating Widget. $exception');
    }
  }
```

**Comment by leonardocustodio** [comment]
This part in the swift file: 
private let widgetGroupId = "nct_home_widget"

Should be your appgroup and not the string that you provide in the updateWidget. So it must starts with: group.something
People usally make something like: group.com.inovatso.picPics.Widget (group + your reverse bundle id + something)

Also did you add the app group to the main target as well as to the plugin?

**Comment by huytower** [comment]
Hello,

I tried as your recommend,
Rebuilt but it did not work.

Please see these images to correct me.

Thanks,

**Code**
![Screen Shot 2020-12-18 at 16 13 51](https://user-images.githubusercontent.com/11640136/102602486-30664880-4154-11eb-8e75-54e9660c424f.png)
![Screen Shot 2020-12-18 at 16 14 18](https://user-images.githubusercontent.com/11640136/102602496-32c8a280-4154-11eb-8ad2-738ae1776eb9.png)

***.entitlements**
![Screen Shot 2020-12-18 at 16 56 42](https://user-images.githubusercontent.com/11640136/102602547-44aa4580-4154-11eb-8f3c-91cd43251b4f.png)

**App Group**
![Screen Shot 2020-12-18 at 16 14 43](https://user-images.githubusercontent.com/11640136/102602594-55f35200-4154-11eb-95fb-9ce6c5e6bb8e.png)
![Screen Shot 2020-12-18 at 16 12 16](https://user-images.githubusercontent.com/11640136/102602603-57bd1580-4154-11eb-9864-978b91110af7.png)

**Comment by ABausG** [comment]
Could you try to solve the issues pointed out by Xcode?

**Comment by sharath12345678** [comment]
Facing the same issue.

Double checked all the setup details and done everything as per docs.

here is the code sample

```

1. Future<void> _saveHomeWidget(title01, mesaage01) async {
2.     try {
3.       print('Save value Started');
4.       return Future.wait([
5.         HomeWidget.saveWidgetData<String>('title', title01),
6.         HomeWidget.saveWidgetData<String>('message', mesaage01),
7.       ]).then((value) => {
8.         print('SAVED Value'), 
9.         print(value)
10.         });
11.     } on PlatformException catch (exception) {
12.       debugPrint('Error Sending Data. $exception');
13.     }
14.   }
15. 
16.   Future<void> _updateWidget() async {
17.     try {
18.       print('update value Started');
19.       return HomeWidget.updateWidget(
20.               name: 'HomeWidgetForSys',
21.               androidName: 'HomeWidgetForSysAndroid',
22.               iOSName: 'HomeWidgetForSys')
23.           .catchError((error) {
24.         print('error');
25.       }).then((value) => {
26.         print('UPDATED Value'),
27.          print(value)
28.          });
29.     } on PlatformException catch (exception) {
30.       debugPrint('Error Updating Widget. $exception');
31.     }
32.   }
33. 
34.   Future<void> _retrieveData() async {
35.     try {
36.       print('retrieve value Strted');
37.       return HomeWidget.getWidgetData<String>('message', defaultValue: 'data')
38.           .then((value01) => {
39.             print('RETRIEVED Value'), 
40.             print(value01)
41.             });
42.     } on PlatformException catch (exception) {
43.       debugPrint('Error Retrieving Widget. $exception');
44.     }
45.   }
46. 
47.   Future<void> _sendAndUpdate(title01, mesaage01) async {
48.     await _saveHomeWidget(title01, mesaage01);
49.     await _retrieveData();
50.     await _updateWidget();
51.   }

```
Here the snapshot of print statement
![Screenshot 2021-04-07 at 3 48 05 PM](https://user-images.githubusercontent.com/54023637/113851183-df3c9c00-97b8-11eb-8049-d0039aa4ec07.png)

Note that values are saving and even the retrieving(getWidgetData<>) is also working, but the widget is not updating.

Few more details
Flutter version - 2.0.4 - stable
XCode - 12.4
home_widget - latest

Any other details, if needed will be provided.

**Comment by ABausG** [comment]
Could you also provide the code of your iOS Widget?
Also a Screenshot of the signing portion in Xcode to make sure the app group is setup correctly?

**Comment by sharath12345678** [comment]
Hi,

find the attached

![Screenshot 2021-04-10 at 9 45 24 AM](https://user-images.githubusercontent.com/54023637/114258098-e266a080-99e1-11eb-97a5-a40a704b3bbc.png)


iOS Widget code // used home-widget example code

 ```
import WidgetKit
 import SwiftUI

  private let widgetGroupId = "group.homewidget.sernal"

 struct Provider: TimelineProvider {
     func placeholder(in context: Context) -> SimpleEntry {
         SimpleEntry(date: Date(), title: "My Goal",
                     message: "Add your goal from Sernal main Screen")
     }

     func getSnapshot(in context: Context, completion: @escaping (SimpleEntry) -> ()) {
         let data = UserDefaults.init(suiteName:widgetGroupId)
         print("getSnapshot")
         let entry = SimpleEntry(date: Date(), title: "My Goal",
                     message: data?.string(forKey: "message")
                     ?? "Add your goal from Sernal ")
         completion(entry)
     }

     func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> ()) {
        //To check here to update widget data
         getSnapshot(in: context) { (entry) in
             let timeline = Timeline(entries: [entry], policy: .atEnd)
             completion(timeline)
         }
        
     }
 }

 struct SimpleEntry: TimelineEntry {
     let date: Date
     let title: String
     let message: String
 }

 struct HomeWidgetForSernalEntryView : View {
     var entry: Provider.Entry
     let data = UserDefaults.init(suiteName:widgetGroupId)

     var body: some View {
         VStack.init(alignment: .leading, spacing: nil,
         content:{
             Text(entry.title).font(.body)
             Text(entry.message).bold().font(.title)
             .widgetURL(URL(string: "HomeWidgetForSernal://openmainscreen"))
         })
     }
 }

 @main
 struct HomeWidgetForSernal: Widget {
     let kind: String = "HomeWidgetForSernal"

     var body: some WidgetConfiguration {
         StaticConfiguration(
             kind: kind,
             provider: Provider()) { entry in
             HomeWidgetForSernalEntryView(entry: entry)
             .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color.gray)
         }
         .configurationDisplayName("My Goal")
         .description("Your added goals are displayed like this.").supportedFamilies([.systemMedium, .systemLarge])
     }
 }

 struct HomeWidgetForSernal_Previews: PreviewProvider {
     static var previews: some View {
         HomeWidgetForSernalEntryView(entry: SimpleEntry(date: Date(), title: "My Goal",
                     message: "My added Goals."))
            .previewContext(WidgetPreviewContext(family: .systemMedium))
     }
 }
```

**Comment by ABausG** [comment]
I think you are missing the App Group Capability in your App.

Go to:
Signing & Capabilities > +Capabilities > App Group

**Comment by sharath12345678** [comment]
App group is in both runner & widget, please find the attached.

![Screenshot 2021-04-12 at 9 16 52 AM](https://user-images.githubusercontent.com/54023637/114338648-1c19e180-9b71-11eb-833e-f7dab0977d19.png)

![Screenshot 2021-04-12 at 9 18 12 AM](https://user-images.githubusercontent.com/54023637/114338547-e37a0800-9b70-11eb-8df5-12da64398131.png)

**Comment by ABausG** [comment]
The Widget seems to only declare the App Group for Profile Builds, not sure if that might be it?
Also just to make sure: You did add the App Group on the Apple Developer Page?

**Comment by sharath12345678** [comment]
Thanks for your time & patience.

Now it is working.

**Comment by ABausG** [comment]
@huytower Does this help you as well?

**Comment by ihadabs** [comment]
For those how might encounter this problem as @ABausG said, make sure to add the app groups to debug, profile, and release.

Make sure you select all:
![image](https://user-images.githubusercontent.com/34512743/114795048-6af49080-9d96-11eb-9433-6501c851013f.png)

See here its not added to the debug:
![image](https://user-images.githubusercontent.com/34512743/114795066-7778e900-9d96-11eb-953f-f26fcb8e329b.png)


When add to all it will look like this:
![image](https://user-images.githubusercontent.com/34512743/114795104-8bbce600-9d96-11eb-9f73-75054129e425.png)

@ABausG Thanks man!

**Comment by huytower** [comment]
let me check in next week.
