### ISSUE TITLE
Add rest api based data to title and message

### ISSUE THREAD

**Issue by makrockon** [ABausG/home_widget#82]
I want to show rest json based api data on home screen widget any one help on it.

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:home_widget/home_widget.dart';
import 'package:workmanager/workmanager.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class User {
  final String title;
  final String message;

  User(this.title, this.message);

  User.fromJson(Map<String, dynamic> json)
      : title = json['title'],
        message = json['message'];

  Map<String, dynamic> toJson() => {
    'title': title,
    'message': message,
  };
}

String title ="not nummsdfs";
String message="notnullmess";
Future<void> getRequest() async {
  //replace your restFull API here.
  String url = "http://103.203.137.49:7001/RecruitmentService/ksbclDetails";
  final response = await http.get(Uri.parse(url));

  Map<String, dynamic> data = new Map<String, dynamic>.from(json.decode(response.body));
  print("data['title']");
  print("mayank"+data['title']);
  print(data['message']);
  //title = data['title'];
  //message = data['message'];
}

/// Used for Background Updates using Workmanager Plugin
void callbackDispatcher() {
  getRequest();
  Workmanager.executeTask((taskName, inputData) {
    return Future.wait<bool>([
      HomeWidget.saveWidgetData(
          'title',
          title
      ),
      HomeWidget.saveWidgetData(
          'message',
          "message"
      ),
      HomeWidget.updateWidget(
        name: 'HomeWidgetExampleProvider',
        iOSName: 'HomeWidgetExample',
      ),
    ]).then((value) {
      return !value.contains(false);
    });
  });
}

main()  {
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
  runApp(MaterialApp(home: MyApp(),debugShowCheckedModeBanner: false,));
}

class MyApp extends StatefulWidget  {
  const MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp>  {

  @override
  void initState() {
    super.initState();
    HomeWidget.setAppGroupId('YOUR_GROUP_ID');
    HomeWidget.registerBackgroundCallback(backgroundCallback);
    getRequest();
    _loadData();

  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _checkForWidgetLaunch();
    HomeWidget.widgetClicked.listen(_launchedFromWidget);
  }

  @override
  void dispose() {
    super.dispose();
  }

  Future<void> _sendData() async {
    try {
      return Future.wait([
        HomeWidget.saveWidgetData<String>('title', "titlesend"),
        HomeWidget.saveWidgetData<String>('message', "message"),
      ]);
    } on PlatformException catch (exception) {
      debugPrint('Error Sending Data. $exception');
    }
  }

  Future<void> _updateWidget() async {
    try {
      return HomeWidget.updateWidget(
          name: 'HomeWidgetExampleProvider', iOSName: 'HomeWidgetExample');
    } on PlatformException catch (exception) {
      debugPrint('Error Updating Widget. $exception');
    }
  }

  /// Called when Doing Background Work initiated from Widget
  void backgroundCallback(Uri data) async {
print(backgroundCallback);
    if (data.host == 'titleclicked') {
      //  final selectedGreeting = greetings[Random().nextInt(greetings.length)];
      final selectedGreeting = title;
      await HomeWidget.saveWidgetData<String>('title', "mayankback");
      await HomeWidget.updateWidget(
          name: 'HomeWidgetExampleProvider', iOSName: 'HomeWidgetExample');
    }
  }

  Future<void> _loadData() async {
    try {
      return Future.wait([
        HomeWidget.getWidgetData<String>('title', defaultValue: 'Default Title')
            .then((value) => "titleload"),
        HomeWidget.getWidgetData<String>('message',
            defaultValue: 'Default Message')
            .then((value) => "message"),
      ]);
    } on PlatformException catch (exception) {
      debugPrint('Error Getting Data. $exception');
    }
  }

  Future<void> _sendAndUpdate() async {
    await _sendData();
    await _updateWidget();
  }

  void _checkForWidgetLaunch() {
    HomeWidget.initiallyLaunchedFromHomeWidget().then(_launchedFromWidget);
  }

  void _launchedFromWidget(Uri uri) {
    if (uri != null) {
      showDialog(
          context: context,
          builder: (buildContext) => AlertDialog(
            title: Text('App started from HomeScreenWidget'),
            content: Text('Here is the URI: $uri'),
          ));
    }
  }

  // void _checkForWidgetLaunch() {
  //   //   HomeWidget.initiallyLaunchedFromHomeWidget().then(_launchedFromWidget);
  //   // }

  // void _launchedFromWidget(Uri uri) {
  //   if (uri != null) {
  //     showDialog(
  //         context: context,
  //         builder: (buildContext) => AlertDialog(
  //               title: Text('App started from HomeScreenWidget'),
  //               content: Text('Here is the URI: $uri'),
  //             ));
  //   }
  // }

  void _startBackgroundUpdate() {
    print("backgorud");
    Workmanager.registerPeriodicTask('1', 'widgetBackgroundUpdate',
        frequency: Duration(minutes: 1));
    constraints: Constraints(
      networkType: NetworkType.connected,
    );
  }

  @override
  Widget build(BuildContext context) {
    getRequest();
    _loadData();
    return Scaffold(
      appBar: AppBar(title: Text("KSBCL")),
      body: Center(
        child:  Text("message"),
      ),
      drawer: Drawer(
        child: ListView(
          // Important: Remove any padding from the ListView.
          padding: EdgeInsets.zero,
          children: [
            const DrawerHeader(
              decoration: BoxDecoration(
                color: Colors.blue,
              ),
              child: Text('Drawer Header'),
            ),
            ListTile(
              title: const Text('Item 1'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer
                Navigator.pop(context);
              },
            ),
            ListTile(
              title: const Text('Item 2'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer
                Navigator.pop(context);
              },
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by ABausG** [comment]
Could you possibly format the code a bit?
In general you should be able to do the following though:

```dart
final networkData = await fetchDataAndExtractString();
await HomeWidget.saveWidgetData<String>('key', networkData);
```

Please let me know if this has helped.
