### ISSUE TITLE
new compilation error in flutter 3.0.0

### ISSUE THREAD

**Issue by sunalwaysknows** [ABausG/home_widget#83]
```
e: D:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\home_widget-0.1.5\android\src\main\kotlin\es\antonborri\home_widget\HomeWidgetPlugin.kt: (19, 1): Class 'HomeWidgetPlugin' is not abstract and does not implement abstract member public abstract fun onNewIntent(p0: Intent): Boolean defined in io.flutter.plugin.common.PluginRegistry.NewIntentListener
e: D:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\home_widget-0.1.5\android\src\main\kotlin\es\antonborri\home_widget\HomeWidgetPlugin.kt: (193, 5): 'onNewIntent' overrides nothing
```

**Comment by josepedromonteiro** [comment]
@sunalwaysknows I created a PR https://github.com/ABausG/home_widget/pull/84 to fix this, meanwhile you can try to use my fork https://github.com/josepedromonteiro/home_widget

**Comment by sunalwaysknows** [comment]
> @sunalwaysknows I created a PR #84 to fix this, meanwhile you can try to use my fork https://github.com/josepedromonteiro/home_widget

good, It works.

**Comment by szastavnyy** [comment]
> @sunalwaysknows I created a PR #84 to fix this, meanwhile you can try to use my fork https://github.com/josepedromonteiro/home_widget

Please explain how to use fork instead of pub.dev released build. thx

**Comment by josepedromonteiro** [comment]
> > @sunalwaysknows I created a PR #84 to fix this, meanwhile you can try to use my fork https://github.com/josepedromonteiro/home_widget
> 
> Please explain how to use fork instead of pub.dev released build. thx

@szastavnyy Sure.
In you pubspec.yaml instead of this

`
  home_widget: ^0.1.5
`

change it to

`home_widget: `
&nbsp;`git:`
 &nbsp;&nbsp;`url: https://github.com/josepedromonteiro/home_widget`

I strongly recommend that when this is fixed in this repository, that you go back to the pub.dev version. This fix may not work in flutter versions previous to 3.0.0.

**Comment by sunalwaysknows** [comment]
> > @sunalwaysknows I created a PR #84 to fix this, meanwhile you can try to use my fork https://github.com/josepedromonteiro/home_widget
> 
> Please explain how to use fork instead of pub.dev released build. thx

@szastavnyy you can use it in this way in pubsepc.yaml
![image](https://user-images.githubusercontent.com/86180691/168255591-d0c29a5f-4167-448a-9414-8506f9ff3a7b.png)
```
  home_widget:
    git:
      url: https://github.com/josepedromonteiro/home_widget.git #change to your git url
```
