### ISSUE TITLE
Update data when app is in killed state

### ISSUE THREAD

**Issue by vishaldhaduk4495** [ABausG/home_widget#9]
Is there any way or example for update widget data on interval when app is killed.

**Comment by leonardocustodio** [comment]
I don't think you can do that on iOS, you would need to store all things on the widget and then change on it based on time.
But on Android one option is to use background_fetch and then call this plugin updateMethod to send the new data.
Take a look on this plugin https://pub.dev/packages/background_fetch

**Comment by vishaldhaduk4495** [comment]
Using the work manager it's working even when app killed.
https://pub.dev/packages/workmanager

**Comment by ABausG** [comment]
I added a section to the (README)[https://github.com/ABausG/home_widget/blob/main/README.md) to describe support for this as well as extending the example app
