### ISSUE TITLE
how to use background callback in ios?

### ISSUE THREAD

**Issue by TONYCHOU81905** [ABausG/home_widget#97]
Hi ~

Does anybody knows how to run home widget background callback in ios?
(It works in Android, but not works in ios)
Thanks a lot!

**Comment by armandojimenez** [comment]
It works for me on iOS simply with this:
`    HomeWidget.widgetClicked.listen(_widgetBackgroundCallback);
`

**Comment by ABausG** [comment]
Unfortunately iOS does not offer support for "interactive" widgets so right now there is unfortunately no way of running code without opening the app after clicking widget elements.
For detecting opening the app it should work as @armandojimenez wrote

**Comment by TONYCHOU81905** [comment]
Thank you both for your answers!
